### ISSUE TITLE
Expand E2E Tests Once Auth Issue Addressed

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#101]
We have two issues, #52 and #64, to address before we can start adding/expanding our e2e tests. But until that is done, it is easy to forget certain e2e tests you want to write.

For example, I was writing unit tests from some functionality added to the experiment list table. But the test is more appropriate in an e2e test than a unit test. (Note: https://w11i.me/next-js-userouter-testing could be a way to test route changes in unit tests.)

- [x] Test that clicking an experiment table row navigates the user to the experiment details page.

**Comment by yanirs** [comment]
@dhurlburtusa Since we're skipping the auth for now, can't we add e2e tests for other parts of the UI?

**Comment by dhurlburtusa** [comment]
@yanirs I haven't tried yet. I'll test it out.

**Comment by dhurlburtusa** [comment]
I misunderstood exactly what was going on with the auth not being tested. It turns out that we can test in development and CI as if the authentication has already happened. Closing.
