### ISSUE TITLE
Address Over-Bundling Issue

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#104]
With some of the libraries we are using, we are importing in much more than we are actually using from the library.

For example, `import _ from 'lodash'` imports the entire library despite us only use a dozen or less of its functions. Doing individual imports of each function (e.g., `import pick from 'lodash/pick'`) addresses the over-bundling, but it makes the code longer and we lose the namespacing that helps minimize name collisions.

You can run `npm run analyze` to get a visualization of what is going into the bundle.

There are many ways to address this issue. Some include
1) Import only what you need.
2) Babel plugin to transform imports in a way to only import what is needed.
3) Configure bundler (Webpack) to tree shake unused code.

See https://material-ui.com/guides/minimizing-bundle-size/, https://www.npmjs.com/package/@material-ui/codemod#optimal-imports.

This is an optimization. So, we should wait until later to address.

**Comment by jessie-ross** [comment]
I would say this is something unnecessary for our requirements - we don't need to worry about the bundle size as this is an internal app and will never need to be SEO optimised. 

I propose we close this.

**Comment by yanirs** [comment]
Yeah, I agree.
