### ISSUE TITLE
Handle API Errors

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#123]
Currently, there is no API error specific handling in place -- only the page layout and app-level error boundaries.

See the discussion starting at https://github.com/Automattic/abacus/pull/115/files?file-filters%5B%5D=.ts&file-filters%5B%5D=dotfile#r439070572

Some known errors to handle:

400 - BadRequest
401 - Unauthorized
403 - Forbidden
404 - NotFound
409 - Conflict
501 - NotImplemented

**Comment by yanirs** [comment]
@jessie-ross was this closed by #438?
