### ISSUE TITLE
Re-Enable Tests Once Test API Returns Adequate Data

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#124]
Related to #116.

- [ ] Re-enable the "called with an unknown metric ID should throw a NotFoundError" test in `__tests__/api/MetricsApi.test.ts`.

**Comment by aaronyan** [comment]
@yanirs do you know if we can close this or consolidate it with https://github.com/Automattic/abacus/issues/506 (and maybe https://github.com/Automattic/abacus/issues/116)?

**Comment by yanirs** [comment]
#506 is unrelated, but it can be consolidated with #116.

**Comment by yanirs** [comment]
Closing in favour of #116
