### ISSUE TITLE
Determine Whether Event Props Should Only Return Strings

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#125]
A potential bug was detected. See https://github.com/Automattic/abacus/pull/115#discussion_r438368439.

Not yet sure whether the bug is with the API. Need to determine what are the expected datatypes for the `prop` property for an `Event` schema.

**Comment by yanirs** [comment]
@dhurlburtusa I'm not sure where you saw a boolean returned, but event props are strings. I see that the mock is returning strings. Closing this issue. If you encountered the boolean with the production API, please open an internal issue with the specific link and we'll address it.
