### ISSUE TITLE
Add basic metric creation page

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#13]
Aaron edited:

Consider building metric details page first (#162). We can consider making the metric creation just be an empty metric details page.

## Metric creation:
- name (snake case, lowercase)
- description
- indicator for `is_higher_better` (checkbox or slider button for on/off)
- radio box for kind of metric (revenue vs conversion)

### Revenue metric:
- refund days dropdown (1, 3, 7, 30) 
- transaction types checklist (can select multiple) (new purchase, recurring, cancelation, etc). Ping @aaronyan for full list.
- product slugs dropdown (but allow additional slugs to be added/removed with a +add product button)
- all fields optional (I think)

For future iteration, make refund days and transaction types options populated by API endpoint.

### Conversion metric:
- event name (form field, with future autocomplete) - allow events to be added/removed with a +add event button
- property name and values (form field with future autocomplete) - allow properties to be added/removed with a +add property button
- properties are attached to events and events can have multiple properties
- only one event name is required

**Comment by jessie-ross** [comment]
Can we cut this down a bit, especially since this won't be used by end users:

Instead of in depth revenue and conversion parameter controls, can we have a single "Params" textbox where directly type in the corresponding JSON, with live validation happening over that JSON.

**Comment by aaronyan** [comment]
A simplified metric creation sounds good to me! Let's also add a skeleton of the JSON for the "params" textbox that changes depending on the type of metric (revenue vs conversion).

So metric creation will then have these fields:
- name (snake case, lowercase)
- description
- indicator for `is_higher_better` (checkbox or slider button for on/off)
- radio box for kind of metric (revenue vs conversion)
- params JSON textbox

If we go the JSON skeleton route, they could look like this:

Conversion metric
```
[
    {
        "event": "event_name",
        "props": {
                "prop_key": "prop_value"
        }
    }
]
```

Revenue metric
```
{
    "refund_days": 7,
    "transaction_types": [],
    "product_slugs": []
}
```

**Comment by yanirs** [comment]
I don't think we should cut it down and use JSON editing:

* The conversion event props are the same as what we need to support adding exposure events (#262 &ndash; a higher priority issue), so we will have a component for that.
* The revenue event props aren't too nested and should be simple to implement as a proper form.

**Comment by jessie-ross** [comment]
@aaronyan Yep, that is exactly right.

@yanirs It is basically instant to add it with JSON editing, can't we improve it later?

**Comment by yanirs** [comment]
I don't see the point in adding with JSON editing for the reasons I specified. Also, we already have an interface with JSON editing: The API console.

**Comment by aaronyan** [comment]
> The conversion event props are the same as what we need to support adding exposure events (#262 – a higher priority issue), so we will have a component for that.

Good point! Since we'll have the event conversion forms in #262, I don't think we should cut down the metric creation to only support JSON anymore. By the end of the milestone, I think we should have metric creation with the proper forms (conversion and revenue creation).

> It is basically instant to add it with JSON editing, can't we improve it later?

I personally prefer forgoing the JSON step and waiting to add in depth revenue and conversion parameter controls, but I don't think it will make a significant difference; it's just a matter of preference for order of operation.

That being said, @jessie-ross if it's useful to your workflow to wrap up the first pass of metric creation by adding the JSON  before working on #262, I would support it. I think it comes down to personal workflow, and if quickly adding the JSON now to wrap up the first pass of metric creation would help get started on #262, then I think it's a pretty good trade off. :) We also don't have any a12s actively using Abacus and the feature is designed for our private use, so I think we can accommodate some personal workflow preferences here.

**Comment by aaronyan** [comment]
I'm reviewing the milestone, and thought it might be nice to summarize what else is needed here to close this issue:
- [ ] Create an event component that was used for [exposure event in experiment creation](https://github.com/Automattic/abacus/pull/278/files?file-filters%5B%5D=.snap&file-filters%5B%5D=.ts#r477081607)
- [ ] Add [metric validation](https://github.com/Automattic/abacus/pull/269#issuecomment-678007204)
- [ ] Create a revenue component for revenue-based metrics (sibling to the event or conversion component)
- [ ] Add the components to metric creation

**Comment by jessie-ross** [comment]
From these comments it looks like the consensus is that we can implement it as JSON now.
But from some slack messages I am not too sure, so I might bring this discussions back.

I still think it is worth doing it as a JSON for now:
- It is not trivial to refactor the Exposure Events control from experiment edit (the data format is annoying and it requires transforming from an object to an array of object, among other things).
- Can't personally foresee any other area that will use events, it would be nice to avoid the refactor at the moment.
- It isn't complicated to add in Revenue Params but it will still take time and will have more moving parts.

**Comment by yanirs** [comment]
Yeah, let's implement it as JSON for now and open a separate issue to address the items from [@aaronyan's comment](https://github.com/Automattic/abacus/issues/13#issuecomment-687309700). We can do that once we have more users adding metrics.

**Comment by aaronyan** [comment]
I'm splitting this issue so that **this one can be resolved once the JSON piece is added**. We can add the `event` and `revenue` components later (less priority).

**Comment by jessie-ross** [comment]
I might close this off since we have this is functional with remaining parts split into #324 and #325

**Comment by jessie-ross** [comment]
Ah oops, not sure why I thought the PR was merged.
