### ISSUE TITLE
Auth code shouldn't be storing tokens in localStorage

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#132]
Auth code is currently storing our Auth tokens in localStorage.
https://github.com/Automattic/abacus/blob/831534c2ce5daed09bdb7cc6d2be64d05e1410e8/utils/auth.ts#L26

Storing secure tokens in localStorage is unsafe as it can be accessed by any any other code running on the site:
https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-storage-on-client-side

**Comment by yanirs** [comment]
Thanks @jessie-ross! We actually had a discussion around switching to `sessionStorage` in #57, but we decided against it. I'll reopen that issue, copy what you said, and comment over there, as #57 has more context.
