### ISSUE TITLE
Add segment management pages

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#15]
We'll probably need to break this up. It's less of a priority at the moment, as we don't expect segment management to be required for most experiments.

**Comment by dhurlburtusa** [comment]
Are there going to be some predefined segmentations for a12ns to use?

**Comment by yanirs** [comment]
Yep, we bulk created a bunch of segments on the backend, which is why this issue is a low priority. :slightly_smiling_face:

**Comment by yanirs** [comment]
Closing this as it looks like segment management will be more of a backend thing for the foreseeable future.
