### ISSUE TITLE
E2E Test Coverage Silently Failing

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#152]
When CircleCI runs the e2e tests, the coverage part fails because the JSX has not been parsed. However, this parse failure does not fail the tests. It prints the errors but does not fail the tests.

Some possible solutions:
1) Add the `ts-jest` to `globals` in `jest.e2e.config.js`.
2) Remove coverage for e2e tests. 

The snippet for #\1:
```
  globals: {
    // Must specify a custom tsconfig for tests because we need the TypeScript
    // transform to transform JSX into js rather than leaving it as JSX which the
    // next build requires.
    'ts-jest': {
      babelConfig: true,
      tsConfig: '<rootDir>/tsconfig.jest.json',
    },
  },
```

After further testing, it looks like the test coverage doesn't work the same as with integration and unit tests. So, it looks like the solution is to disable coverage for E2E tests.

Note: The reason why this appeared to be working correctly before new routes/pages were added was because we were ignoring all these files.

**Comment by yanirs** [comment]
@dhurlburtusa would a more accurate title be "E2E test _coverage_ failing silently"? Is 1 a viable solution or should we just go with 2?

**Comment by dhurlburtusa** [comment]
@yanirs After further investigation, we should remove the Jest coverage mechanism and add in one specifically to work with Puppeteer. I'm working on that now.
