### ISSUE TITLE
Exclude Any Method Regardless of Signature

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#156]
We have declared a TypeScript type that picks all properties of another type excluding a method with a single parameter. But we want to exclude any function regardless of the number of parameters.

This bug was discovered when trying to add a new method that takes a parameter.

**Comment by jessie-ross** [comment]
It looks like this is a workaround that is needed because we are using classes for the data models.
I suggest implementing them as interfaces instead, it should lead to simpler and more consistent code.

I am going to write up a P2 on this with an example shortly.

**Comment by yanirs** [comment]
@jessie-ross they were interfaces before, but we moved away from this because we wanted to add methods.
