### ISSUE TITLE
Add metric details page

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#162]
A page to view metric details:
- Displays rich details of metric (resolves #149)
- Allow inline editing (resolves #14)

Let's follow the same design as the experiment details:
- Metric: <metric_name> at the top left
- A single General card with all of the details shown in expanded metric experiment page view
- Leaving out the edit button until we support metric editing

<img width="512" alt="experiments-view-with-tabs-and-metric-details" src="https://user-images.githubusercontent.com/4505888/85796786-61a71400-b6ef-11ea-809a-b9100dd4d966.png">

For future iterations, we can consider a card below General showing all of the experiments that use this metric (needs API endpoint).

**Comment by yanirs** [comment]
> Metric name at top left

Should we make it `Metric: <metric_name>`? We currently have `Experiment: <experiment_name>` for experiment pages. This is useful because it's also used for the page title and it's not always clear from the name if it's a metric or an experiment.

> Edit button top right

Shall we leave this out until we support editing?

> For future iterations, we can consider a card below General showing all of the experiments that use this metric (needs API endpoint).

:+1:

**Comment by aaronyan** [comment]
Thanks for the suggestions. Accepted all and edited the original description per your suggested changes:
- make it Metric: <metric_name>
- leave out edit button until we support metric editing

**Comment by jessie-ross** [comment]
I have sort of implemented this already using the grid expansion feature.
Do we need this implemented further, would it make sense to wait for needing edit capabilities?

**Comment by aaronyan** [comment]
Yeah, I think the way you've implemented the grid expansion feature is good enough for now. +1 let's wait for a need to edit before we add a metric details page.

I'd like to see the grid expansion in the Experiment Overview tab, but I'll create a separate issue for that. Lowering the priority on this issue for now.

**Comment by jessie-ross** [comment]
Especially since this is only going to be accessible by "Admin"s (us), I recommend doing this by a single modal that is used for both adding and editing:
- Edit button in the metric rows.
- Add button under the table.

**Comment by yanirs** [comment]
If we put it on the `/metrics` page then it'll be accessible to everyone, no?

**Comment by jessie-ross** [comment]
I thought we were going to be putting this behind some kind of wall, might just be a request parameter.

**Comment by yanirs** [comment]
Ah, makes sense. :slightly_smiling_face: No objections to doing it as a modal if we hide it behind a request parameter.

**Comment by aaronyan** [comment]
> Especially since this is only going to be accessible by "Admin"s (us), I recommend doing this by a single modal that is used for both adding and editing

I'm a bit confused. Is this proposing we only add a modal to the [add metric](https://github.com/Automattic/abacus/issues/13) and [edit metric](https://github.com/Automattic/abacus/issues/14)? or also add a modal to the metric details view?

Since we already have grid expansion for details view, I'm not a huge fan of having a modal right now. But if it makes the add metric and edit metric easier, then I say we go for it. Especially if the modal makes it easier for the permissions side of things.

> Especially since this is only going to be accessible by "Admin"s (us)

And just to make sure we're all on the same page. The add/edit will be admin only, but the view details should be accessible to everyone. I can P2 some of these role definitions if we'd like to formalize these roles and discuss permission levels.

**Comment by jessie-ross** [comment]
> I'm a bit confused. Is this proposing we only add a modal to the add metric and edit metric? or also add a modal to the metric details view?


What I was thinking is that we only have the metric list view, with the details available on expansion - no metric details view for now.

At the end of each metric row there will be an edit button, at the bottom of the grid there will be an add button.


> Since we already have grid expansion for details view, I'm not a huge fan of having a modal right now. But if it makes the add metric and edit metric easier, then I say we go for it.

Yep, using the modal should make development and the code simpler as we aren't switching between edit components with view components all over the place. This is especially useful if we are still changing the view parts, which we will be.

>  Especially if the modal makes it easier for the permissions side of things.

It doesn't happen to make much difference as far as permissions.

**Comment by aaronyan** [comment]
Awesome, thanks for the extra details. I think we're all on the same page! Closing this issue since the metric details are in the place where we want them for now: **details available on grid expansion of metrics list.**
