### ISSUE TITLE
Consider moving away from nested tables in AudiencePanel

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#163]
See https://github.com/Automattic/abacus/pull/160#discussion_r445348674 and https://github.com/Automattic/abacus/pull/160#discussion_r445345622

**Comment by aaronyan** [comment]
I don't have any strong opinions on how this should be technically implemented. I'd be willing to sacrifice some looks/visualizations for better practices if the costs comes down to that.

**Comment by aaronyan** [comment]
@jessie-ross, can we close this?

**Comment by yanirs** [comment]
Closing since the nested tables have served us well so far. :slightly_smiling_face:
