### ISSUE TITLE
Add Schema library

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#165]
After some [discussions](https://github.com/Automattic/abacus/pull/85#issuecomment-647438438), we've decided to use a Schema library! 

Happy to break this issue up into smaller issues if we want to work on adding this in steps. Feel free to let me know or edit this description if I'm understanding incorrectly. I think we'll need schema definitions for each schema class in our API?
- [ ] Analysis
- [ ] Error?
- [ ] ExperimentBare
- [ ] ExperimentCreate
- [ ] ExperimentFull
- [ ] Event
- [ ] MetricBare
- [ ] MetricAssignment
- [ ] MetricEstimate
- [ ] PatchRequest? (maybe later, we don't have PATCH implemented yet)
- [ ] Platform
- [ ] Segment
- [ ] SegmentAssignment
- [ ] Status
- [ ] Variation

Quoting some of the benefits:

> They provide run-time schema validation and coercion which means:
> 
> - We can validate the items coming in from the server.
> - Currently we have no validation
> - We can type coerce the values coming from the server, i.e. dates
> - We can provide user-level validation for forms
> - We can perform integration tests
> 
> The overall benefits would be:
> 
> - Reduced code duplication across server validation, coercion, user validation, and integration testing.
> - We get run-time tests at the boundaries of our system ensuring the data coming in is as we expect.

**Comment by jessie-ross** [comment]
I would also suggest at the same time moving from classes to just interfaces, it would make this transition simpler and reduce the duplication of code.

@yanirs, mentioned using classes because of wanting methods and I would like to make a plea for a more function approach. Can I ask what the rational for needing methods was?

**Comment by yanirs** [comment]
It's natural to have helper methods in the context where they're used. That is, if a function always operates on an instance of an interface, it might as well be a method. I don't see a good reason for having a bunch of functions floating around &ndash; not a fan of functional purism (or a purist adherence to any programming paradigm for that matter). :slightly_smiling_face: 

I'm also wary of making a huge change right now. However, I'm happy to look at a PR that demonstrates what you have in mind.

**Comment by jessie-ross** [comment]
Implemented by #204
