### ISSUE TITLE
Add Test Framework for Unit Tests

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#17]
Probably Jest? This should include adhering to [this file structure](https://sergiodxa.com/articles/next-file-structure/) and setting it up to run as a required CI check.

**Comment by dhurlburtusa** [comment]
The testing setup wasn't the easiest thing to figure out given that we want it to work with Jest, Next.js, TypeScript, Testing-Library, and React.

https://github.com/zeit/next.js/tree/canary/examples/with-jest shows a Next.js project using Jest and Testing-Library but not with TypeScript.

https://github.com/zeit/next.js/tree/canary/examples/with-typescript shows a Next.js project using TypeScript but nothing about testing.

https://www.pluralsight.com/guides/how-to-test-react-components-in-typescript helped but didn't exactly work with Next.js. One take-away was a simpler way of test setup files. The `setupFilesAfterEnv` in `jest.config.js` was the result.

https://medium.com/@kjaer/setting-up-jest-and-enzyme-for-typescript-next-js-apps-ce383167643 shows how with Next.js, Jest, TypeScript, and Enzyme. This is the closest I found and switching out Enzyme for React Testing-Library was simple enough. This guide explains why we have two TypeScript configuration files.
