### ISSUE TITLE
Support updating an experiment's details

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#195]
See #179 for buttons/toolbar we can use. The idea is to only allow editing specific fields depending on the status. When the time comes to implementation, I think it's worth discussing again whether we want to do it via inline editing.

**Comment by jessie-ross** [comment]
Following on from my suggestions on #196, I find having the edit button on top a bit unintuitive so I would like to suggest an alternative approach here.

**For a staging experiment,** for the MVP, I see no problem with reusing the experiment creation wizard and I have built it for that purpose. The edit button will take them to the same wizard with all their fields pre-filled. The text would just need to be changed slightly.

**For a non-staging experiment**:

<img width="796" alt="Screen Shot 2020-08-18 at 1 56 15 pm" src="https://user-images.githubusercontent.com/971886/90475868-ef850580-e15a-11ea-92c5-bad0765e4447.png">


- Having Seperate edit buttons for each section (general and adding metrics).
- Use modal forms for these changes.

My reasoning:
- There is no disconnect between the overall form controls and the 
- It is clear what is editable.
- It is simple to disable the add-metrics button after completion.
- We can include a tooltip as well indicating why different things are disabled, teaching our Experimenter.
- Modals provide much better code separation and will be cleaner to implement.
- Modals forms are a very well known pattern.


To go further with this:
- Again I would love to see "General" and "Audience" split into "Metadata", "Experiment Parameters", and "Audience", I think it will make the UI behaviour make even more sense
- Keep the top-level "Edit Experiment", "Conclude Experiment" and the general-panel "Edit" and metric-panel "Add Metric" in there all the time, but show them as disabled when they are not available (with tooltips saying why). This can be nice UI as the buttons are always in the same spot and you learn what is available and when.

**Comment by jessie-ross** [comment]
Ah it also makes a lot of sense with the tab design.

**Comment by yanirs** [comment]
I like the idea of separate buttons and modals. 

Not entirely sure about "going further":

> Again I would love to see "General" and "Audience" split into "Metadata", "Experiment Parameters", and "Audience", I think it will make the UI behaviour make even more sense

I don't see how this separation would help, as the description and owner can always be edited, and the end date can be edited while the experiment is running.

> Keep the top-level "Edit Experiment", "Conclude Experiment" and the general-panel "Edit" and metric-panel "Add Metric" in there all the time, but show them as disabled when they are not available (with tooltips saying why). This can be nice UI as the buttons are always in the same spot and you learn what is available and when.

It's possible to add secondary metrics to experiments that already ended. They take a maximum of 24 hours to backfill, but we can implement backfilling on demand at some point.

I think it'd be a bit confusing to add disabled buttons that would never get enabled, e.g., `Edit` for a non-staging experiment, but I'm not too fussed. Can see how it goes.

**Comment by aaronyan** [comment]
> For a staging experiment: The edit button will take them to the same wizard with all their fields pre-filled

I like it! Sounds good to me for the MVP.

> For a non-staging experiment:
> - Having seperate edit buttons for each section (general and adding metrics).
> - Use modal forms for these changes.

This also sounds good to me! Makes sense to move edit to this modal view since we are restricting edits for non-staging experiments.

> Keep the top-level "Edit Experiment", "Conclude Experiment" and the general-panel "Edit" and metric-panel "Add Metric" in there all the time, but show them as disabled when they are not available (with tooltips saying why). This can be nice UI as the buttons are always in the same spot and you learn what is available and when.

+1, I like the idea of not adding/removing, but only disabling with a reason. I'm down for those the top-level actions being:
- Edit
- Disable
- Conclude

**Comment by jessie-ross** [comment]
@aaronyan, that makes good sense!

Although I think I would like to seperate the wizard editing from the panel editing (not having the redirects to the creation wizard):

How about changing the top level edit to "Edit in Wizard" so Experimenters know what they are in for and that they can edit the whole experiment like they did before?

I am fine with the conclusion "redirect" as it will just be opening the modal.

**Comment by aaronyan** [comment]
Ah good point in keeping the wizard editing separate from panel editing. In that case, let's forgo the edit buttons for the Audience and Conclusions panel.

I like the "Edit in Wizard" idea! We can see how that goes and adjust accordingly.

**Comment by aaronyan** [comment]
I'm reviewing the milestone, and thought it might be nice to summarize what else is needed here to close this issue:
- [ ] Assign metrics submission (addressed in #297)
- [ ] Add Edit in Wizard (addressed in #304 and #306)
- [ ] Run an experiment by clicking top-level button

**Comment by yanirs** [comment]
Good summary, @aaronyan! Should also disable the edit buttons based on the experiment's status.

I think that @jessie-ross is planning to cover it all in the coming days, but if not we should probably split this issue.

**Comment by aaronyan** [comment]
Good call, edited the summary comment to include:

> Disable the edit buttons based on the experiment's status

**Comment by jessie-ross** [comment]
I think this one is done :)

**Comment by yanirs** [comment]
Yep! :partying_face:
