### ISSUE TITLE
Support concluding an experiment

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#196]
See #179 for buttons/toolbar we can use. The general idea is to support populating the experiment's conclusion fields if they're empty and the experiment's status is `completed` or `disabled`.

**Comment by jessie-ross** [comment]
With the current UI in Figma the conclusion controls and the conclusion form are strangely disconnected:

![Markup 2020-08-18 at 13 42 14](https://user-images.githubusercontent.com/971886/90474800-b3e93c00-e158-11ea-8aaf-3143d86d8601.png)
 

For UI I would like to suggest something like GitHub's review button:
<img width="719" alt="Screen Shot 2020-08-18 at 1 39 28 pm" src="https://user-images.githubusercontent.com/971886/90474629-489f6a00-e158-11ea-8f74-e306404d35f5.png">

We can use [MUI's popover](https://material-ui.com/components/popover/)

This should be more intuitive for the user and result in simpler code.

**Comment by yanirs** [comment]
I agree with improving the connection between the two components, but I'm not sure I follow how it'd work. Currently, we don't show the conclusion panel if the experiment hasn't been concluded, so do you mean we'd have the `Add Conclusion` button with popover in this case? If so, it sounds good to me.

How will we support editing the conclusions? With a separate edit button for the conclusion panel, as suggested in #195? If so, I like it. :slightly_smiling_face:

**Comment by jessie-ross** [comment]
> How will we support editing the conclusions? With a separate edit button for the conclusion panel, as suggested in #195? If so, I like it. 🙂

Yep I think that would be good.

> Currently, we don't show the conclusion panel if the experiment hasn't been concluded, so do you mean we'd have the Add Conclusion button with popover in this case?

Yeah I was thinking of having this at the top in the "toolbar" opposite the tabs, but now that I think about it further we could have an empty "Conclusion" panel with an green Add conclusion button in it.

**Comment by jessie-ross** [comment]
I might include @withinboredom and @aaronyan for this and #195
