### ISSUE TITLE
Copy Prettier and other useful settings from Calypso

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#2]
Alternatively, we can just set Prettier up based on widespread community standards rather than the more WordPress-y feature store settings.

**Comment by dhurlburtusa** [comment]
@yanirs Prettier has very few configuration and that is by design. I can add Prettier to the project along with its ESLint plugin.

What is the feature store dashboard and how do I get to it to copy the settings?

**Comment by yanirs** [comment]
> What is the feature store dashboard and how do I get to it to copy the settings?

We can actually copy settings from [Calypso](https://github.com/Automattic/wp-calypso/). I adjusted the title accordingly.

Note that Calypso uses `wp-prettier` and there are currently discussions to drop it, so I'm inclined to use the official Prettier for now with our own settings. Can always adjust later.
