### ISSUE TITLE
Empty error boxes appearing on /experiment/[id] and /metric/[id]

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#200]
Following up on Yanir's comment at pbmo2S-oh-p2#comment-912.

Replicating:
1. Visit https:/.../experiments/1 or https://.../metrics/1 directly

There are two problems going on here:
1. It looks like pages are being rendered with null path properties initally:
    <img width="1416" alt="Screen Shot 2020-07-07 at 11 46 13 am" src="https://user-images.githubusercontent.com/971886/86717900-2b558700-c055-11ea-8078-aa12f45ed05e.png">
    This might be a bug with the router loading the page before fully initialising.    
2. Error messages aren't being reset.
    I think the solution to this is to [use Snackbars](https://material-ui.com/components/snackbars/)

**Comment by yanirs** [comment]
This was fixed by @jessie-ross in #206 and #209.
