### ISSUE TITLE
Apply consistent object normalisation across the codebase

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#201]
Mapping nested objects (e.g., metrics to an experiment's metric assignments) is currently handled inconsistently throughout the code. @jessie-ross suggested we use [normalizr](https://github.com/paularmstrong/normalizr) for this.

See: https://github.com/Automattic/abacus/pull/198#discussion_r449975708

**Comment by jessie-ross** [comment]
Also see #204 which would give us a structure for grouping functions that operate on related data-types.

**Comment by yanirs** [comment]
@jessie-ross should we close this or are you still planning on addressing this issue at some point?

**Comment by jessie-ross** [comment]
Hmm, it is actually not so bad in practice, especially with the refactoring, maybe not worth it. At the very least low priority.

**Comment by yanirs** [comment]
Closing based on this discussion. We can always refactor on a per-need basis.
