### ISSUE TITLE
Audit and reduce useMemo usage

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#202]
From [a PR comment](https://github.com/Automattic/abacus/pull/198#discussion_r450323318) by @jessie-ross:

> I don't think we need to be using so many `useMemos`:
> 1. The front-end is very fast and these aren't expensive operations.
> 2. It is extremely easy to add a bunch of them on later.
> 3. These ones don't add much since their dependencies are the same as the Components they sits within. 

This is somewhat related to #201, as some of the `useMemo` calls wrap normalisation functions.

**Comment by jessie-ross** [comment]
Yep I think we can just be on the lookout for them and remove them progressively.

**Comment by yanirs** [comment]
Closing since this is likely to happen as part of other work rather than as a distinct issue.
