### ISSUE TITLE
Considering our grid library

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#205]
I saw we considered a lot of "React" grids earlier but we didn't consider some general JavaScript grid libraries, of which there are some big players.

A solid one of note is: https://www.ag-grid.com/
It is one I have used before, it is very well designed and maintained and works well with React.
It has an open source core with a commercial version including extra-features on top.
The open version should be fine.

I don't think we need to change it now but it may be good to plan for a transition.
They tend to have very similar column-definition data structures among them but differ in their special features.

**Comment by jessie-ross** [comment]
Material table is currently unmaintained but has been forked as https://github.com/material-table-core/core

**Comment by aaronyan** [comment]
@jessie-ross, can we close this now with the introduction of https://github.com/Automattic/abacus/pull/497? :)

**Comment by yanirs** [comment]
I think it's OK to close given that the main experiment table now uses ag-grid. We can change other tables if and when we touch them.

**Comment by jessie-ross** [comment]
Oh sorry, I missed this ping.
