### ISSUE TITLE
Add exposure events and status to experiment details view

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#217]
In the experiments details view, we forgot to include the `exposure_events` and `status`! :) 

Let's add `exposure_events` to the Audience card with the current grouping design. Set as low priority for now in case we change the grouping design.

And let's add `status` as it's own row to the General card right above `Dates`. We can use the same `ExperimentStatus` component that is used in the Experiments List.

**Comment by yanirs** [comment]
@aaronyan I bumped the priority to high because not being able to see exposure events is a blocker to setting up some experiments.
