### ISSUE TITLE
Set up Circle CI

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#22]
Configure CI to run static checkers (linters and formatters) and tests.

The CircleCI config at may be useful https://github.com/cypress-io/cypress-and-jest-typescript-example.

Other possibly useful links:
https://github.com/Automattic/wp-calypso/blob/master/.circleci/config.yml
https://github.com/Automattic/wp-e2e-tests-gh-bridge

**Comment by dhurlburtusa** [comment]
@yanirs I have a CircleCI account and because I have access to the A8c organization on GitHub, I can see many of the A8c jobs and projects. I can also see Abacus in the [section to add Abacus as a project](https://app.circleci.com/projects/project-dashboard/github/Automattic) but the tooltip says the repo admin needs to set it up.
Will you do that for me? Thanks.

**Comment by yanirs** [comment]
@dhurlburtusa I set up the project on CircleCI, which auto-generated the config file on the `circle-ci-setup` branch. The only change I made to the config was replacing `npm test` with `npm run test:unit -- --coverage`. I opened PR #37 to ensure it runs when PRs are pushed.

Can you please take over the PR to finish the setup (or start your own branch and config)? You should also be able to [test the CircleCI setup locally](https://circleci.com/docs/2.0/local-cli/), which is faster than pushing to the branch for every change. :slightly_smiling_face:
