### ISSUE TITLE
Mock data ids aren't self-consistent

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#226]
From this comment: https://github.com/Automattic/abacus/pull/224#pullrequestreview-452705870

The `id`s in our mock data aren't matching up so errors are being thrown when they are found to be missing.

It is just a matter of changing them in the swagger docs.

**Thoughts about the underlying issues:**

In the future it would be nice if we had a public real server with "real" mock data in the database, it is always best to develop and test against the real thing. Right now the first time it meets a real server is after deploy, which is a worry. (This is the real problem behind #224.)

If that isn't possible I would suggest at least having programmatically generated mock data using a local-to-the-abacus-repo mock server. This isn't as much work as it sounds as we already have programmatically generated mock data. This would further centralise things and make it easier to test - it is going to be important to have some level of persistence to do useful experiment creation e2e tests. In general we should also be changing and adding to the mock data as we need to test different cases, so we want to make that as easy as possible.

I don't see any particular benefit to using swagger as a mock server as it is just documentation and isn't any more guaranteed to match production behaviour than having the local mock server.

**Comment by yanirs** [comment]
> It is just a matter of changing them in the swagger docs.

Can you please do this?

> In the future it would be nice if we had a public real server with "real" mock data in the database, it is always best to develop and test against the real thing. Right now the first time it meets a real server is after deploy, which is a worry. (This is the real problem behind #224.)

Yeah, I think we discussed it in a few places before. I agree it's a problem, but as a temporary solution it is possible to make local changes and test manually against the production server. It's far from ideal, but should be good enough for getting the basics in. Later (in a month or two?), we should set up a more robust solution to at least run some basic sanity checks against the production server.

Regarding the local mock, I'm not a fan of maintaining yet another mock server, but we do have an issue to look into moving away from SwaggerHub. One potential solution is to move the API docs to this repo, generate at least a part of the mock server from the docs, and run it locally to Abacus. This would resolve some of the maintainability/consistency problems, but I see it as a lower priority for now.
