### ISSUE TITLE
Make it easy to run locally with the production API

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#228]
As noted by @scjr in https://github.com/Automattic/abacus/pull/227#pullrequestreview-453020865, it'd be good to add a switch that allows us to run locally against the production API, probably with a strong warning that this is what we're doing:

> If we are frequently testing on Production servers it might also be a good idea to add on a switch that makes it easy for us to do so. It can be a double edged sword especially if we are editing/creating data as mistakes can be made, it would be good if it was super obvious that we are using production endpoints such as with a red banner.

**Comment by jessie-ross** [comment]
We should also add a test in that runs before other tests, checking that our test suites never accidentally run on production data.

**Comment by jessie-ross** [comment]
Fixed by #252
