### ISSUE TITLE
Fix Vercel PR preview returns mismatch in redirect_uri

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#261]
When clicking on the [deployed PR by Vercel,](https://public-api.wordpress.com/oauth2/authorize?client_id=68795&redirect_uri=https%3A%2F%2Fabacus-mg4m2okkn.vercel.app%2Fauth&response_type=token&scope=global) I'm getting the error below. I get this error on all the PRs I've tried viewing the deployed preview. @jessie-ross, any ideas what may be causing this?

<img width="785" alt="Screen Shot 2020-08-11 at 4 15 53 PM" src="https://user-images.githubusercontent.com/4505888/89958204-30769a80-dbee-11ea-8d91-da48cefd9f17.png">

**Comment by jessie-ross** [comment]
Ah! This is an authentication error, it must have broke after #252 

Currently Vercel is using a production config profile so it is trying to authenticate but Vercel's `redirect_uri` is not added to the WP authentication server.

The solution is to change the Vercel build script to add the env variable: `NEXT_PUBLIC_NODE_ENV_OVERRIDE=development`

**Comment by jessie-ross** [comment]
I have added the variable to Vercel and fixed this issue:
https://d.pr/i/N7D43c

**Comment by aaronyan** [comment]
Awesome, thanks for taking a look and making that fix @jessie-ross!
