### ISSUE TITLE
Metric Assignment UI should prevent duplicates.

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#275]
From 417-gh-experimentation-platform#discussion_r476260844.

Since Metric Assignments should be unique over the tuple `(metricId, attributionWidowSeconds)` we should ensure this occurs on the front-end:
- Hide already used combos
- Add a check into the schemas

**Comment by yanirs** [comment]
@jessie-ross do you think this is still worth doing now that we're showing backend errors? I don't see any harm in a roundtrip to the server to get the error if an experimenter decides to do something silly like adding the same metric assignment twice. :slightly_smiling_face:

**Comment by jessie-ross** [comment]
Yep sounds like a reasonable solution :)

Let's reopen if/when we hear back about this.
