### ISSUE TITLE
Speeding up experiment fetches

### ISSUE THREAD

**Issue by withinboredom** [Automattic/abacus#294]
This is a small quality of life improvement for experimenters. However, we could use [`React Helmet`](https://github.com/nfl/react-helmet) to add a `<link  rel="prefetch"` to the head to preload the api request for their latest experiment when landing on the "home page". It probably needs some experimenting to see if it actually works and it would probably be a good idea to instrument the application first.

**Comment by jessie-ross** [comment]
I think prefetching and getting into caching should be used as a last resort for us, caching makes everything quite complicated and for an app like this I think we can avoid it entirely.

I can see two performance problems:
1. Any time we change the tab in an experiment it reloads, this is a problem with NextJs architecture and although there are ways around it I think it will be best to remove it, see #212. 
2. It is pretty slow to get the data.

The first problem is my main annoyance and I think removing it would significantly improve perceived performance

### A look into the slow data requests

I accidentally got a bit too interested in this part, even though it is not important right now.

This is the timing profile of a request for an experiment (taken as an average example out of a few):

<img width="744" alt="Screen Shot 2020-09-04 at 1 09 29 am" src="https://user-images.githubusercontent.com/971886/92146273-0e1e1880-ee4c-11ea-83c7-d3af1403cbae.png">

There are two things of interest here, the long queue time, and the long wait time.

Let's consider the wait time first, this includes the round trip lag so let's account for that first, this is my poor Aussie lag:

<img width="555" alt="Screen Shot 2020-09-04 at 1 11 54 am" src="https://user-images.githubusercontent.com/971886/92146507-6b19ce80-ee4c-11ea-9a0d-f2d3d1f5b385.png">

It is significant but it isn't enough to cover it, it looks like the server is taking up 200ms during processing, that strikes me as a lot so there should be room to shave there.

This brings me to the queuing time:

<img width="1157" alt="Screen Shot 2020-09-04 at 1 10 00 am" src="https://user-images.githubusercontent.com/971886/92146879-f2674200-ee4c-11ea-83dd-f933af0ecaf8.png">

The reason there is a huge queuing time is that an `OPTIONS` request for `CORS` details needs to be made first as we are performing cross-origin request. In the screenshot above that is the 4 from the highlighted row.

Again the round trip lag is only a third of the request wait time. Given that it is such a simple request it is strange it has `~200ms` of overhead.

**Comment by jessie-ross** [comment]
It looks like adding `ACCESS-CONTROL-MAX-AGE` will improve things somewhat, although the max is 10 minutes. 
See https://stackoverflow.com/a/40373949

**Comment by jessie-ross** [comment]
Since we have dropped Next.JS I don't think this is an issue any more - and things feel responsive enough to me.
