### ISSUE TITLE
Investigate flaky CircleCI tests

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#331]
We're seeing [CircleCI tests fail on unrelated code](https://github.com/Automattic/abacus/pull/328#issuecomment-694741002). Probably something worth looking into to improve the quality of life when developing PRs.

**Comment by yanirs** [comment]
Given that this is taking up a significant amount of time, I think it's worth escalating and doing soon. My guess is that we're hitting the limits of the CircleCI container, so there are a few things to look at:

- Allocating a bigger container (we'll need to pay for it, but Automattic has a paid account)
- Reducing memory use (there might be some simple tweaks)
- Checking why "rerun from failed" reruns the entire flow

Any objections to doing it this milestone?

**Comment by yanirs** [comment]
> Checking why "rerun from failed" reruns the entire flow

Ah, this is because we have a single-job workflow: https://circleci.com/docs/2.0/workflows/. We should be able to somewhat alleviate the pain of rerunning failed steps by breaking up the job into parallel workflow jobs.

**Comment by jessie-ross** [comment]
I've just upped the timeouts for now which makes this a bit better

**Comment by yanirs** [comment]
Thanks @jessie-ross! It does seem more stable, so I'll downgrade this to `medium` for now.

**Comment by yanirs** [comment]
Between @jessie-ross's timeout tweak and the changes in #350, I think we can close this issue and address further tweaks separately (#48 #293 #351).
