### ISSUE TITLE
Metric edit JSON populated with [object Object]

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#332]
In production, trying to edit an existing revenue/conversion metric on Firefox populates the field with `[object Object]`:

![Peek 2020-09-21 15-02](https://user-images.githubusercontent.com/3952615/93734259-d7058080-fc1b-11ea-9a53-6b4e28a90ce8.gif)

This may also be a problem on Chrome. I haven't checked. :slightly_smiling_face:

**Comment by jessie-ross** [comment]
Yeah this is because it isn't quite implemented yet - implemented in #329.
This was because of how I decided to split the PR for easier reviewing but it wasn't feature complete.
