### ISSUE TITLE
Fix debug mode styling

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#341]
@jessie-ross: The new debug header introduced in #337 has some weird styling when loading from /experiments. Can you help me take a look and see if you can reproduce?

Loving the new way to toggle debug mode on though (shift + double click footer)! 😄 
 
<img width="1359" alt="Screen Shot 2020-09-23 at 2 22 28 PM" src="https://user-images.githubusercontent.com/4505888/94086987-3d1f0e80-fda8-11ea-8643-317e32bdd6b9.png">

## To reproduce

1. Visit /experiments not in debug mode
2. Activate debug mode
3. View strangely styled debug mode header

Or

1. Visit /experiments while in debug mode
2. Shift + Cmd + R to hard refresh (bypass cache)
3. View strangely styled debug mode header

**Comment by yanirs** [comment]
@aaronyan we discussed this on the PR: https://github.com/Automattic/abacus/pull/337#issuecomment-697142399

**Comment by aaronyan** [comment]
Ah I see. Thanks for the context @yanirs. Closing for now.
