### ISSUE TITLE
Look into using CircleCI parallelism

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#351]
See: https://circleci.com/docs/2.0/parallelism-faster-jobs/ and https://circleci.com/blog/a-guide-to-test-splitting/. Our plan allows for 25 parallel runs, but we're only using one.

**Comment by aaronyan** [comment]
With #331 merged, I think we can close this. With the parallel runs, tests can be rerun now without rerunning everything. Nice work!

**Comment by yanirs** [comment]
@aaronyan this isn't the same thing &ndash; see the linked resources. I opened this issue _after_ #350 for a reason. :slightly_smiling_face:

**Comment by yanirs** [comment]
Moved to #544.
