### ISSUE TITLE
Trend plots are unclear when there are results from a single day

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#355]
Looking at https://abacus-git-add-participant-graph.a8c.vercel.app/experiments/1/results, it's unclear that experimenters need to hover over the graphs to see the results. We can fix it by `lines+markers` for the participant plot and hiding the other plots when there's only one day of results, but there are a bunch of other options. Thoughts @jessie-ross?

**Comment by aaronyan** [comment]
I like the `lines+markers` approach! :)

**Comment by jessie-ross** [comment]
Closed by #443
- Lines+Markers
- Hiding the metric plots
