### ISSUE TITLE
Add tag CRUD UI

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#360]
Once we have the tag API endpoints defined in Swagger, we can implement a simple interface to view and manage tags (probably similar to metrics), which will be debug-only at first.

**Comment by jessie-ross** [comment]
**Here are my thoughts on this:**

I see three places where we will want to introduce tags:

- Experiment Creation Form: Basic Info
- Experiment: General Panel
- Experiment: General Panel: Edit

And for new UI components:
- A custom tag chip for display tags as a tag is two pieces of data, the namespace and the name.
- Tag input component: using our existing autocomplete but customising the rendering of the auto-complete item (using `renderOption`) as a tag chip. Seems like we just need to allow in custom `getOptionSelected` and `getOptionValue`.

There will also need to be some minor schema changes but that is all straightforward.

**Comment by yanirs** [comment]
@jessie-ross this issue is for managing the tags. Assigning them to experiments is #361. :slightly_smiling_face: That said, we might want to combine the two and allow inline creation.

> Experiment: General Panel: Edit

We won't need this initially, as the only tags are exclusion group tags that must be assigned ahead of the experiment (as part of creation or when editing `staging` experiments).

**Comment by jessie-ross** [comment]
> this issue is for managing the tags. 

Ahhh I see.

**Comment by aaronyan** [comment]
https://github.com/Automattic/abacus/pull/370 🎉
