### ISSUE TITLE
Add exclusion tag assignment to the creation/full-edit form

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#361]
Once we have the tag API endpoints defined in Swagger,<sup>*</sup> we can extend the experiment creation/full-edit form to support assignment of exclusion tags (`namespace='exclusion_group'`) in debug-only mode. 

<sup>*</sup> We may want to hold off until the assignment API is fully implemented.

**Comment by jessie-ross** [comment]
Posting this here after mistakenly putting it in #360.

**Here are my thoughts on this:**

I see three places where we will want to introduce tags:

- Experiment Creation Form: Basic Info
- Experiment: General Panel
- Experiment: General Panel: Edit

And for new UI components:
- A custom tag chip for display tags as a tag is two pieces of data, the namespace and the name.
- Tag input component: using our existing autocomplete but customising the rendering of the auto-complete item (using `renderOption`) as a tag chip. Seems like we just need to allow in custom `getOptionSelected` and `getOptionValue`.

There will also need to be some minor schema changes but that is all straightforward.

**Comment by jessie-ross** [comment]
Yanir mentioned about the General Panel Edit in https://github.com/Automattic/abacus/issues/360#issuecomment-707564381:

> We won't need this initially, as the only tags are exclusion group tags that must be assigned ahead of the experiment (as part of creation or when editing staging experiments).

This is interesting, I didn't think of this and it complicates the tag behaviour quite a bit. For me this is a point towards using a seperate metadata field in the future.

**Comment by yanirs** [comment]
> This is interesting, I didn't think of this and it complicates the tag behaviour quite a bit. For me this is a point towards using a seperate metadata field in the future.

Why does it complicate things more than any other field that can be changed on new experiments but not later (like segments)?

**Comment by jessie-ross** [comment]
This is a bit different to segments as we have one field that behaves in seperate ways depending on what we are setting. 
An equivalent for segments would be if locales and countries behaved separately and could be edited at different times.

**Comment by yanirs** [comment]
Ah, I see. Initially we're probably only going to have exclusion group tags (and maybe `internal/code_ready`), so I think it's fine for now. If we add tags that can be applied to non-staging experiments, we can figure out how to best approach it, as it really depends on the semantics of the tags. As noted before, I think we should avoid overusing tags.

One possible solution to simplifying things on the API and client level is to abstract the tags away, e.g., in experiment we would have `exclusive_group_tag_ids` as a list of tag IDs and `code_ready` as a boolean field, but on the backend they would be saved as tags. It may be YAGNI at this point, but I might play with the API definitions to see how it goes.

**Comment by jessie-ross** [comment]
_I have mentioned splitting our experiment creation/display sections further before when I brought up an "Experiment Metaparameters" section, but that particular incarnation wasn't well received._

**I think it is worth revisiting our experiment "sections" as we are adding more configuration in and planning for even more:**

How about something like this:
* Basic Info
* Audience
* Assignment Options
   * Variations
   * Exclusion Groups
* Metrics
* (At a later stage) Analysis Options
   * Exposure Events

The effort involved to do so is very minimal, including both changing Experiment Overview and Experiment Creation.

**Comment by aaronyan** [comment]
For now, I think we should simply add exclusion groups to "Audience". It's pretty simple and low cost to make sure we're not blocking that feature from arriving in Abacus. A redesign of the sections can happen, but I think we should do it later and with certain goals in mind.

@jessie-ross if you're interested in starting that discussion for a future revision to experiment sections, I think it's probably best as a P2 post! I'm actually a fan of your new sections, but it's unclear to me the motivation and benefits from changing it up, so please add some context and background to why you think these changes are valuable for us to work on (and when you think we should work on it).

**Comment by jessie-ross** [comment]
Update:

Adding tags to creation/assignment is a small change on top of the tags CRUD, I am going to wait for the current PRs to go through but this is how it is looking:

<img width="1324" alt="Screen Shot 2020-10-26 at 3 52 22 pm" src="https://user-images.githubusercontent.com/971886/97146725-50583c00-17a3-11eb-9620-d4f4051fdae9.png">

**Comment by aaronyan** [comment]
Woo! Looking great!

**Comment by yanirs** [comment]
I believe this is done. :slightly_smiling_face:
