### ISSUE TITLE
Change platform option to read "wpcom"

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#379]
When selecting a Platform on Experiment Creation, I think we should use the word "wpcom" instead of "WordPress.com". This is just a personal preference, because I associate "wpcom" with the PHP backend, whereas I associate "WordPress.com" with "Calypso".

This issue was created because there's been a couple of times where I select the wrong platform. 😄  Is this just me?

## Action items

- [x] Discuss whether to adjust the platform to be "wpcom" instead of "WordPress.com"
- [ ] Implement or close issue

**Comment by yanirs** [comment]
Maybe we should add some help text to specify what's meant by each platform? There's plenty of vertical space to work with, so we can change to `WordPress.com Backend`, or something along these lines.

**Comment by aaronyan** [comment]
> so we can change to WordPress.com Backend, or something along these lines

I like that change too! +1 to using more horizontal space.
