### ISSUE TITLE
Implement copy experiments

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#380]
When building the three experiments for the [Monthly Pricing experiment](https://growthchannels.wordpress.com/2020/09/29/project-thread-monthly-pricing/), it would have been nice to copy an experiment and have it loaded into the Experiment Creation Wizard. The biggest benefit is being able to copy over the metric assignments!

This feature might also be helpful for experimenters getting started with Abacus and ExPlat. 😄 

## The "Copy experiments" experience

When viewing the list of experiments, I think hovering over an experiment will display the ellipses on the right. After clicking on the ellipses, the only available option would be to "Copy experiment".  Clicking "Copy experiment would redirect to the Experiment Creation Wizard with all of the experiment details copied over.

## Action Items
- [ ] Discuss the "Copy experiments" experience
- [ ] Implement it or close issue

**Comment by jessie-ross** [comment]
I've been wanting to have this for a while, this would be extremely simple with CRA so I was waiting to see about that.
