### ISSUE TITLE
Add metric descriptions to experiment overview and creation

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#381]
In the future, let's consider adding tool tips next to metric names in Experiment details Overview. On hover or click of the metric name or tooltip, we can show the metric descriptions!

We can consider adding a "info modal icon" too to indicate that extra information is available upon hover.

**Edit by Yanir**: This should include changes to the following components.

- [x] The creation wizard table
- [x] The creation wizard dropdown
- [x] The overview page table
- [ ] The overview page "assign metric" dialog dropdown

**Comment by yanirs** [comment]
This applies to adding the metrics to an experiment as well. In general, the UI around that should be tweaked, as the number of metrics is now a bit overwhelming.

See also pau2Xa-30h-p2
