### ISSUE TITLE
Add tooltip and link to metrics on experiment details

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#382]
In the spirt of making it easier to understand what metrics do, we should **make metrics expandable and collapsable** in the Experiments Overview page. This allows experimenters to view metric details without having to go to `/metrics`.

We've also discussed an alternative of showing a tooltip on hover of metric names (same as #381). I'm good with this alternative as long as we also show the metric definitions (Tracks events or billing filters).

**Comment by jessie-ross** [comment]
I am thinking now to have the tooltip, but also having the metric name be a link to the expanded metric row in `/metrics` page.

How does that sound?

**Comment by aaronyan** [comment]
Closing this because it is a duplicate here: https://github.com/Automattic/abacus/issues/381
