### ISSUE TITLE
Prevent loading jitters in production

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#387]
When testing out some PRs, I noticed that the UI will jump horizontally whenever links are clicked. It seems to only happen on production. Any idea what may be causing this?

### Production jitters

![Untitled2](https://user-images.githubusercontent.com/4505888/98886321-ac2fef80-2448-11eb-8ffc-452710c40954.gif)

### Vercel development (no jitters)

![Untitled](https://user-images.githubusercontent.com/4505888/98886326-b05c0d00-2448-11eb-9fee-2c9a343390bc.gif)

## Action items
- [ ] Fix/ remove jitters from production when links are clicked or close issue

**Comment by jessie-ross** [comment]
It this is what I think it is, it is the scroll bar.

The scrollbar doesn't appear in vercel as there is not enough data.

I was playing the other day with having an always on scrollbar.

If this was destined for more polish we would would likely have the content within - the table - scroll

**Comment by yanirs** [comment]
Closing since this will be addressed if and when we iterate on the Metrics table.

@aaronyan we can reopen if you feel like it's worth keeping this as a distinct issue.

**Comment by aaronyan** [comment]
Thanks! I'm cool with closing for now. There are a few other places that I see jitters, but they may get addressed as we work on them. Some more examples:

### Viewing experiment details
When clicking on an experiment from experiment directory and going to the experiment details. The "Experiment" header moves every so slightly downwards and to the left.

https://user-images.githubusercontent.com/4505888/120726054-1fa05980-c48c-11eb-89ae-7bfaf1d217a7.mov

### Viewing other tabs in experiment details
When clicking the code setup tab, we see a jitter left and right. I think this is the same "scrollbar" jitter we see between /experiments and /metrics.

https://user-images.githubusercontent.com/4505888/120726154-50808e80-c48c-11eb-9773-1d972f449c3e.mov

### Expanding metric assignments
When expanding a metric assignment, we see the columns shift from left to right.

https://user-images.githubusercontent.com/4505888/120726210-67bf7c00-c48c-11eb-852d-790e8d02f491.mov
