### ISSUE TITLE
Fix formatting issues and lint warnings

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#39]
Fix misc issues: Prettier format, ESLint errors, and misc formatting.

**Comment by yanirs** [comment]
@dhurlburtusa FYI, there's no need to open an issue _after_ opening a PR, especially for trivial things like this. Also see the comment on #38 &ndash; let's not do this until #22 is done.

**Comment by dhurlburtusa** [comment]
@yanirs Awesome! Working on #22 right now.

**Comment by yanirs** [comment]
@dhurlburtusa Great! These minor issues are actually great for testing CircleCI, as the build should fail until they're fixed. :slightly_smiling_face:
