### ISSUE TITLE
Bump up our CircleCI Memory 

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#397]
We occasionally hit some memory limits in CircleCI, let's look into upgrading.

Our current `resource_class` is `medium`, this is `2 vcpu`s and `4gb` of RAM.
The next step up is `medium+` with `3 vcpu`s and `6gb` of RAM.

I have set this resource class in our config but it requires an upgrade to our plan.

[See CircleCI's reference for more info](https://circleci.com/docs/2.0/configuration-reference/#resource_class)

**Comment by jessie-ross** [comment]
Here is a relevant company wide discussion: p7H4VZ-2Bs-p2
It looks like this isn't feasible for now and there is no plan for increasing memory at the moment.
I think we can deal with it as is.

@yanirs I'm ready to close this if you are?

**Comment by yanirs** [comment]
Yeah, let's close this. 

Here's a relevant issue with a bunch of solutions to the excessive memory consumption problem: https://github.com/facebook/create-react-app/issues/8096
