### ISSUE TITLE
Allow "manual analysis" results to be viewed with skippable warnings

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#402]
While investigating the conditions that result in "manual analysis required" (#445), we determined that [we should allow experimenters to see results](https://github.com/Automattic/experimentation-platform/issues/445#issuecomment-726601524) only if we show they agree to a warning. Something like this:

![99045573-488afb00-25dd-11eb-922c-13a4db5b4854](https://user-images.githubusercontent.com/4505888/99323059-3354dd00-2826-11eb-867e-49cbb527a698.png)

## Action items
- [ ] Determine the warning sign text and design
- [ ] Allow "manual analysis" results to be clickable and a warning sign appears
- [ ] Alert us when someone skips the warning

**Comment by aaronyan** [comment]
We also agreed that we should make the **graphs viewable in debug mode**! So graphs that would normally be blocked from view with the "manual analysis required" should be made viewable when in debug mode.

**Comment by yanirs** [comment]
As @jessie-ross noted in 624-gh-Automattic/experimentation-platform#issuecomment-833439288, we can get the same effect by reframing "manual analysis needed" as a health report issue. We can figure out the exact details of what this would look like when the time comes, but I think it's the right direction.

**Comment by aaronyan** [comment]
We haven't encountered manual analysis results in a very long time. I think we can close this if y'all feel comfortable with it.

**Comment by jessie-ross** [comment]
Yep, let's close :)
