### ISSUE TITLE
Show backend errors to the user

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#415]
> There's no harm in leaving the existing name, as the backend will return an error if it isn't changed.

We don't show backend errors yet and it can be quite confusing to the user when a save is rejected.

_Originally posted by @jessie-ross in https://github.com/Automattic/abacus/pull/412#discussion_r533915523_

This is also important in a number of other instances.

**Comment by yanirs** [comment]
Making this a high priority since it's one of these annoying rough edges that we should probably address soon.
