### ISSUE TITLE
Improve result page wording and displayed data

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#419]
The details may be best hashed out in the context of a PR, but here are some ideas:
* [x] The difference interval can be a sentence, e.g., _"There is a 95% probability that the value is between `<bottom>` and `<top>`"_.
* [x] For conversion metrics, the difference interval should be multiplied by 100 to get percent values (consistency with the plots).
* [x] Finish adding a top-level recommendation (#369)
* [x] Consider dropping the strategy.
* [x] Add the variation value ranges (in a sentence?) so that users won't need to hover over the graphs to get them.
* [x] Add details to _"manual analysis required"_, e.g., _"manual analysis required: contact @experimentation-platform-project on #a8c-experiments"_.
* [x] Move the recommendations to the top-level area.
* [x] Make the remaining warnings friendlier.
* [ ] Integrate feedback from Greg: pbmo2S-Fn-p2.

**Comment by jessie-ross** [comment]
By "Replace Python duration warnings with client-side duration warnings and move them to the top-level area.", do you mean doing the calculation in the front-end?

**Comment by yanirs** [comment]
Yeah, it's a trivial calculation (`end_datetime - start_datetime`). I specifically meant ignoring `RecommendationWarning.ShortPeriod` and `RecommendationWarning.LongPeriod` in favour of smarter date warnings. For example, duration warnings are irrelevant for email experiments. The original thinking behind having them in the Python code was to have a single source of truth (in Hypotheses the same duration warnings were calculated in two places), but it's too inflexible and a pain to maintain.

**Comment by aaronyan** [comment]
> The difference interval can be a sentence, e.g., "There is a 95% probability that the value is between <bottom> and <top>".

This wording was helpful for some experimenters, and they also requested it to be added to Abacus result page (pbxNRc-De#comment-1404). Just adding this comment as a vote for this improvement!

**Comment by yanirs** [comment]
Also edited to add a task item to integrate Greg's feedback from pbmo2S-Fn-p2

**Comment by jessie-ross** [comment]
Oooh! After seeking @veekaybee's extended wording it might be good to do this for the difference interpretation:

<img width="875" alt="Screen Shot 2021-02-05 at 9 41 24 am" src="https://user-images.githubusercontent.com/971886/106978081-7922a100-6796-11eb-8552-854d610ecb36.png">

**Comment by yanirs** [comment]
Hmm.. I'm not sure about that. The idea with the ROPE and Kruschke's approach in general is that we can also accept the null hypothesis, so saying that the difference is "practically not significant" isn't the same as saying that it's inconclusive. Also, people have a tendency to misinterpret "not statistically significant" as "statistically insignificant".

I think we can wait to see how we go when we add multiple ranges and then think of changing the wording. However, it may make sense to introduce the positive phrasing in conclusive cases as a start ("the difference is ... This is statistically significant since the difference interval excludes zero, and practically significant since the conversion rate difference is below/above the ROPE.").

**Comment by jessie-ross** [comment]
I've been looking into Greg's feedback and I think an important theme there is providing a more focused view, displaying less in some places, displaying more in other places.

Since we have different user groups that need different information I think moving to a role based results view will be a good solution:
- **Viewer**: Further simplified top level summary, limited experiment health information, simplified metric-assignment views, limited graphs, all metric assignments open.
- **Experimenter**: Experiment Health info, more detailed stats and graphs.
- **Reviewer**: More detailed infomation, manual-analysis viewable, by-analysis pivot under each metric.

At first we can just do this with a radio control at the top and local-storage, this ties in nicely with #402 (Allow manual analysis with warnings) and we can show a warning dialog if a user clicks on Reviewer.

**Comment by jessie-ross** [comment]
Greg also mentioned having high level metric values, and chatting with @aaronyan today I think it is important to add the lift interval to the MetricAssignment table, so it shows as a column when it is closed.

**Comment by jessie-ross** [comment]
> Replace Python duration warnings with client-side duration warnings and move them to the top-level area.

I am going to move this to its own issue as it is more a maintenance task, won't hurt to do later and in #485 have isolated it now to altering the pure function of `getAggregateRecommendation`.

**Comment by aaronyan** [comment]
> Since we have different user groups that need different information I think moving to a role based results view will be a good solution

I like that idea! For now, I think we can stick with two roles: experimenter and reviewer. Where the viewer + experimenter are combined into one. I think we should try leaning closer to the viewer role here, as simplicity tends to translate better for most experimenters. Those that want more advanced access can "graduate" to become part of the experiment review guild and get access to the debug mode for now.

**Comment by jessie-ross** [comment]
> Greg also mentioned having high level metric values, and chatting with @aaronyan today I think it is important to add the lift interval to the MetricAssignment table, so it shows as a column when it is closed.

This is a basic mockup:
<img width="1256" alt="Screen Shot 2021-03-29 at 11 13 58 am" src="https://user-images.githubusercontent.com/971886/112782588-f4f6e680-907f-11eb-8fdf-1ae06b4d5a9a.png">

- We show it with opacity if it is inconclusive
- If it is conclusive, show it as black for deploy any, green for deploy treatment, red for deploy control
- Hover to get interpretation
- Might actually put recommendation at the end

This is in addition to showing the lift under the other intervals when you open up

**Comment by jessie-ross** [comment]
From the discussion on slack p1616987897040300/1616752000.035100-slack-C7HH3V5AS

Yanir asked:
> Why would we elevate the lift to the table level?

I see this as part of the improvements I mentioned here https://github.com/Automattic/abacus/issues/419#issuecomment-806536116

This comes from discussions with Aaron I had about improving UX for executive level users, as well as from looking at Greg's feedback. In general I think it would at least be nice to get the diff up here.


Yanir also mentioned that Lift may not be ideal here:
> @Niranjan I agree it's worth looking at the lift, but please be mindful of avoiding the common pitfall of reporting only the point estimate. Especially with lift and especially with low base rates, getting increases in the hundreds of percents is pretty easy. And despite being a percentage, this makes lift incomparable across metrics.

Hmm, maybe we could put a warning sign after it or signal if there is especially low base rates.

Another option might be @niranjan-uma-shankar's other request:
>2. Is there a way to let Abacus also report the difference interval as annualized incremental cash? E.g. a 95% probability that launching the experiment could lead to incremental cash in the range [ -50K, 700K ] would be helpful to know what we stand to lose or gain in annual revenues from this experiment.

I think this would be quite nice as an executive overview for revenue metrics, it doesn't have the low base rate issue and it comparable across metrics.

**Comment by jessie-ross** [comment]
Yanir also mentioned about the scaled ARPU to AR:
> We can multiply the ARPU estimates by any number of users, but from ExPlat's perspective it's impossible (or very hard) to know what number to use as an estimate. For example, if an experiment was run on a part of Calypso / backend code that's only accessed by a certain percentage of users, and if only a subset of users were targeted, we don't know what the full population would be.

We can scale to the estimated 100% of the targeted audience, and we could mention that in the column label `Additional Annual Revenue (over targeted audience)`

**Comment by yanirs** [comment]
We should be very careful with revenue scaling, as it has the potential to be very misleading. I think we're better off sticking to a self-service approach right now or make it a toggle. It shouldn't make much of a different to most experiments as far as the final decision goes.

> Greg also mentioned having high level metric values, and chatting with @aaronyan today I think it is important to add the lift interval to the MetricAssignment table, so it shows as a column when it is closed.

I still don't understand where this is coming from. We'd be elevating figures that we've hidden on purpose from being completely hidden to being top-level. A warning sign isn't enough &ndash; at the very least, we should show both the difference and the lift.

**Comment by jessie-ross** [comment]
> We'd be elevating figures that we've hidden on purpose from being completely hidden to being top-level. 

Ah I didn't realise diff was supposed to be hidden, or do you mean lift? I thought we were going to include lift anyway 443-gh-Automattic/experimentation-platform ?

> we should show both the difference and the lift.

I think this would be a good solution.

**Comment by yanirs** [comment]
I meant that it's a big switch from not showing lift at all to making it the main thing we show, especially given the stability issues that lift has around small and large values, and other pipeline considerations (like specifying min_diff in metric assignments).

Showing both in the table would be a good solution since it gives enough context and flexibility to make metric-level decisions.

**Comment by aaronyan** [comment]
> Is there a way to let Abacus also report the difference interval as annualized incremental cash? 
> 
> I think we're better off sticking to a self-service approach right now or make it a toggle

The toggle sounds good to me! We could auto-fill the values and allow experimenters adjust the # of users.

We should support revenue scaling, but also take the steps to help protect against misleading information. Tool-tip or `*` all the things!

> Greg also mentioned having high level metric values, and chatting with @aaronyan today I think it is important to add the lift interval to the MetricAssignment table, so it shows as a column when it is closed.
>
> I meant that it's a big switch from not showing lift at all to making it the main thing we show

Yeah, next time we'll try writing down our thoughts somewhere (P2 preferably) to share the context around new proposed ideas so that everyone is on the same page.

In the case of proposing to add lift to the MetricAssignment table, I can share the motivation from my side! When I view experimental results, I (and I've seen other experimenters) have trouble taking action on absolute difference in performance. I crave lift, because it helps me understand and communicate the differences to others. I think displaying a lift interval to the MetricAssignment table would help folks better comprehend all of their metrics.

I think we should be adding the metrics to support our experimenters, even if it opens some doors that could be misleading. We should also take steps to educate and help prevent misinterpretation (like adding automated `*` with warnings about the lift for metrics with small/ large conversion percentages).

> Showing both in the table would be a good solution since it gives enough context and flexibility to make metric-level decisions.

I'm also cool with showing both lift and absolute difference intervals! :)

**Comment by yanirs** [comment]
> Yeah, next time we'll try writing down our thoughts somewhere (P2 preferably) to share the context around new proposed ideas so that everyone is on the same page.

Yeah, as discussed on Slack, let's move to a P2 discussion for the remaining items, as this is drifting far beyond the original idea of this issue, which was to improve the display of existing information.

> With less risky options, we can take steps to educate and help prevent misinterpretation (like adding automated `*` with warnings about the lift for metrics with small/ large conversion percentages).

I don't think that adding too many threshold-based warnings is a good idea, as it may habituate people to ignore warnings completely.

> I'm also cool with showing both lift and absolute difference intervals! :)

OK, we're all on board with this item, but it's beyond the scope of the issue so let's split it up and discuss the exact presentation separately.

**Comment by jessie-ross** [comment]
With the last health indicator PRs merged I am going to close this task and split off addressing the rest of Greg's feedback in #516
