### ISSUE TITLE
Improve date field input and error messages based on feedback from Don

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#423]
In pbmo2S-j2-p2#comment-1377, @donlair said:

> * The test date text field crashed hard every time I tried to enter a date, even if properly formatted. I eventually typed the date in a separate text editor and pasted it in.
> * I had to look at an existing test to see what date format to use.
> * Some input error explanations would be helpful. For example, it took me a minute to realize I needed to manually type a value in the Minimum Difference field, even though there appears to be a default value.

We should investigate the crash with Don and improve the way the wizard works to make it easier to use.

**Comment by jessie-ross** [comment]
> The test date text field crashed hard every time I tried to enter a date, even if properly formatted. I eventually typed the date in a separate text editor and pasted it in.
> I had to look at an existing test to see what date format to use.

Couldn't replicate the date field crash, I pinged Don and found it to be a Safari issue, see this video: https://d.pr/v/hjkWM0

I've let Don know about using Chrome or Firefox as a workaround until this is fixed.

> Some input error explanations would be helpful. For example, it took me a minute to realize I needed to manually type a value in the Minimum Difference field, even though there appears to be a default value.

We could remove or make the placeholder fainter hmm... I think the real fix here is to have the fields validated when the form-part changes. The validation UX is fairly rough around the edges unfortunately.

**Comment by jessie-ross** [comment]
A reply from Don:

> I rotate between safari and chrome so that'll be fine.

**Comment by jessie-ross** [comment]
I've tested this again in Safari and it looks like it is working now whereas it wasn't when I tested it before, so I will mark that part down as done.

There is just the validation issues which should be solved by #567 and #566.
