### ISSUE TITLE
Handle more bookmarklet authorisation scenarios

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#433]
As discussed in https://github.com/Automattic/abacus/pull/431#pullrequestreview-555127522, we should get the bookmarklet to work from authenticated Calypso contexts. However, the current implementation is likely to be good enough for most testing needs, so this is a low priority for now.

**Comment by jessie-ross** [comment]
I'm pretty sure we have this working in our cookies/bookmarklet overhaul, reopen if not.

**Comment by yanirs** [comment]
Yeah, 649-gh-Automattic/experimentation-platform should cover it without going through more complex authentication scenarios. Thanks!
