### ISSUE TITLE
Add tooltips to acronyms on the results page

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#437]
@victorespigares gave us some great feedback on Abacus (pbxNRc-B0#comment-1362), and I think it makes sense to add tooltips to our acronyms on the results page. The acronyms that could use tooltips:

- CI: credible interval
- ROPE: region of practice equivalence

Another option is to reduce the use of acronyms all together, but would require some changes to the backend.

**Comment by yanirs** [comment]
Closing as this has already been partly addressed and will be further address by #524.
