### ISSUE TITLE
Show participant ratio with tooltip

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#441]
We should consider showing the **relative ratio on the participants graph**. It can be displayed in parentheses next to the absolute participant count when hovering over points in the graph.

For example, when we see participant counts, we can show the ratio in parentheses:
- `control`: 200 (0.67)
- `treatment`: 100 (0.33)

This idea came about because it was not very easy to tell that the ratio of the participants just by looking at the graph. If we make this change, we should also consider **adding ratios to the Overview page** next to the variation percentages:
- `control`: 10% (0.67)
- `treatment`: 5% (0.33)

And if we add these ratios, we should have them hover-able with a tooltip explaining that these are the relative ratios.

## Action items
- [ ] Discuss if we want to include these changes
- [ ] Add ratios to participants graph or discard
- [ ] Add ratios to Overview variations section or discard

**Comment by yanirs** [comment]
Rather than changing the graph, I think it may be worth showing the latest ratio as part of the top-level panel, which goes well with the work @jessie-ross has planned in https://github.com/Automattic/abacus/pull/369#issuecomment-758004359. We should also include the expected range for the ratio, and an SRM warning if it deviates from what we expect.

**Comment by aaronyan** [comment]
Adding the participant ratios to the top-level panel sounds like a great idea to me! I could see that top-level panel grow to have more top-level summaries to help experimenters digest their experiment results.

**Comment by yanirs** [comment]
Closing as this was addressed more robustly by the Health Report checks.
