### ISSUE TITLE
Cover debug mode in tests

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#457]
In general, debug mode is meant for experiment reviewers, so it should be treated like other production code and be tested.

We should audit any `istanbul ignore` comments where debug mode is uncovered, remove them, and add tests.

**Comment by jessie-ross** [comment]
My thinking here is that we create a seperate "Advanced Mode" or "Reviewer Mode" which is Experimenter accessible/for Reviewers under the planed warning dialog, and we make sure everything in advanced mode is tested.

We leave debug mode for use by ExPlat developers for in-progress features/unreleased features and displaying test data.

**Comment by yanirs** [comment]
Closing since we are moving towards separate handling of Advanced/Reviewer Mode (with test coverage), as noted by @jessie-ross.
