### ISSUE TITLE
Add text that only validated events are accepted exposure events

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#462]
Shall we consider having a line of text (or clickable info icon) describing that **only validated events are autocompleted** for exposure events? Having this information available in the experiment creation wizard could help answer some of experimenters questions when they don't find what they're looking for.

I recently forgot this rule and re-learned it by diving into our code. We also recently had an experimenter ask us why their exposure event was not autocompleting in p1612774650033300-slack-C7HH3V5AS.

**Comment by yanirs** [comment]
Sounds good to me!
