### ISSUE TITLE
Missing Analysis Data is crashing the Results tab

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#463]
@aneeshd16 messaged me about Abacus crashing for opening metric assignments with "Missing analysis data".
There were for metrics he had just assigned so they were showing up as "Not analyzed yet"

This happens because we check for any data overall and don't have a check within the metric easy fix.
This isn't blocking anything as there is no data so I am just putting it as medium priority.

**Replicating:**
1. Create experiment
1. Have some analysis data
1. Add a new metric assignment
1. Click on that metric assignment in the Results tab

**Comment by yanirs** [comment]
Agreed with the priority. As part of the fix, it may also be worth differentiating between "Not analyzed yet" (no analyses returned for the metric assignment) and "Insufficient data or analysis failure" (analyses returned, but the metric estimates are null). It's the latter issue in the case reported by @aneeshd16.

**Comment by yanirs** [comment]
Adding another related crash I encountered: If there are analyses for the ITT strategy, but no analyses for the default strategy, the Results tab doesn't load at all.

Like the main issue, this is an edge case that's only likely to occur in manual testing, e.g., if all users are spammers.

**Comment by yanirs** [comment]
> Adding another related crash I encountered: If there are analyses for the ITT strategy, but no analyses for the default strategy, the Results tab doesn't load at all.
> 
> Like the main issue, this is an edge case that's only likely to occur in manual testing, e.g., if all users are spammers.

This was fixed by @aaronyan in the ETL. We now produce analysis rows even when there are no participants.

**Comment by jessie-ross** [comment]
I've moving this to low priority as we have a fix in the backend so isn't impacting experimenters at all.

**Comment by yanirs** [comment]
I'm bumping it back to medium priority since it can still happen in the all-zero or new metric assignment scenario, and this sort of behaviour is poor UX. While the practical impact is low, we should fix it since a front-end crash shouldn't be a part of the normal flow &ndash; it does affect how Abacus and ExPlat are perceived.

**Comment by yanirs** [comment]
@jessie-ross is this fully resolved now?

**Comment by jessie-ross** [comment]
Yep closed by #527
