### ISSUE TITLE
An experiment was created without metrics

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#476]
It seems like @dzver was able to create an experiment without metrics, this shouldn't be able to occur.

See p1615559822070800-slack-C7HH3V5AS for the full chat.

Me, @aaronyan and @dzver have tried replicating it to no avail, so it seems to be quite rare.
Since it's rare, doesn't have any production affects and a workaround exists (recreating an experiment), I am going to label this as low priority.

**Comment by yanirs** [comment]
Let's close this and reopen if we manage to reproduce it.
