### ISSUE TITLE
Help experimenters consider exposure events

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#478]
We can help experimenters consider exposure events for their experiment. Right now, the exposure event in experiment Creation Wizard is labeled as "Optional" and thinking about exposure events for their experiment is easy to ignore.

Here are few ideas that we shared:
- Remove "Optional" text from exposure event section or
- Add info text line in exposure event section informing the value of exposure events or
- Add a required checkbox to confirm exposure events are not needed

This conversation started (p1616002651003700-slack-G01BQ5WMR8Q) when an experiment (pbxNRc-Ir-p2) we found did not have an exposure event, and it would likely benefit from having one.

What do y'all think? Should we help experiments consider exposure events? If so, how?

**Comment by aaronyan** [comment]
I'm a fan of the required checkbox option!

**Comment by is4ac** [comment]
I am currently in the process of adding the required checkbox option. Is that still the consensus for what should be added? Should I also remove the "(Optional)" label from the Exposure Events section, or is just adding the checkbox enough?

Thoughts? @aaronyan @jessie-ross

**Comment by aaronyan** [comment]
Thanks for taking this on @is4ac! I'm a fan of removing "(Optional)". We could also can include a sentence after: "You don't have any exposure events at the moment. We strongly suggest adding one to improve the accuracy of your metrics."

I'm not a big a fan of the checkbox anymore; I think because it requires experimenters to perform another action before moving on. I'm cool with only removing "(Optional)" and adjusting the wording.

**Comment by is4ac** [comment]
> I'm a fan of removing "(Optional)". We could also can include a sentence after: "You don't have any exposure events at the moment. We strongly suggest adding one to improve the accuracy of your metrics."

That makes sense! What about wording it as "We strongly suggest considering adding one...". I would feel cautious about making it seem like every experiment should have an exposure event. Unless there is a history of most experiments needing one?

> I'm not a big a fan of the checkbox anymore; I think because it requires experimenters to perform another action before moving on. I'm cool with only removing "(Optional)" and adjusting the wording.

I agree, the checkbox might not have been the most user friendly solution.

**Comment by aaronyan** [comment]
> What about wording it as "We strongly suggest considering adding one...". I would feel cautious about making it seem like every experiment should have an exposure event.

That wording sounds great to me!
