### ISSUE TITLE
Cache apt-get Call in CircleCI Config

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#48]
It might speed up the CI builds if we cache the apt-get call.

Seems the current solution is to create a custom Docker image. See https://discuss.circleci.com/t/caching-apt-get-intall-results-in-2-0/12883/2 and https://discuss.circleci.com/t/cache-apt-packages/8755.

Note: The suggested solutions in the CircleCI discussions are from 2016 and 2017. Check again to see if that has changed.

Note: It currently takes about 14s to run apt-get for the purpose of installing headless chrome dependencies.

**Comment by yanirs** [comment]
Following my investigation in #350, the best way forward is to use a next-gen image that comes with browsers once that's supported: https://discuss.circleci.com/t/new-ruby-convenience-image-public-beta/33274/6

**Comment by yanirs** [comment]
Moved to #544.
