### ISSUE TITLE
Set up deployment process

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#5]
We can probably use [Vercel](https://vercel.com/) for deploying feature branches, `master`, and a staging branch (`develop`?).

**Comment by dhurlburtusa** [comment]
@yanirs Does A8c have a Vercel/Zeit account we can use for deployment?
What domain do we plan to use?

**Comment by yanirs** [comment]
> Does A8c have a Vercel/Zeit account we can use for deployment? 

Sent you an invite to add you to the team. :slightly_smiling_face: 

>  What domain do we plan to use?

We'll eventually use `experiments.a8c.com`, but for now we can use the default Vercel domains.

**Comment by yanirs** [comment]
Also, thinking about near-term development, we probably don't need a staging setup yet. That is, we can merge feature branches directly to `master` until we have active users.

**Comment by yanirs** [comment]
Closing as the setup is working as expected: https://github.com/Automattic/abacus/pull/41#issuecomment-620268131

**Comment by yanirs** [comment]
> > What domain do we plan to use?
> 
> We'll eventually use `experiments.a8c.com`, but for now we can use the default Vercel domains.

Added https://github.com/Automattic/abacus/issues/42 to deal with it later.
