### ISSUE TITLE
Improve Results Page - Pt 2

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#516]
Split from #419 

The last remaining part was integrating feedback from Greg, which I think comes down to these tasks:

- [ ] Adding legends to the graphs
- [x] Showing the Diff + Lift in the the metric assignment rows
- [x] Reducing the displayed information in general - I think the best way to do this is to start introducing some roles (see https://github.com/Automattic/abacus/issues/419#issuecomment-806536116).
- [x] Showing CI interpretations in tooltips

**Comment by jessie-ross** [comment]
We have some further feedback from @robertbpugh in pbxNRc-V1-p2#comment-2302:

- Legends for the charts
- More links for more information/hover

It also looks like it wasn't clear that the metric assignments could be opened, which may have contributed to his other points.

**Comment by jessie-ross** [comment]
For legends for the graphs, I see two options:
1. Add custom graphs using D3.
2. Add legends separate to our graph library under the graphs.

**Comment by aaronyan** [comment]
Closing this issue and created https://github.com/Automattic/abacus/issues/648
