### ISSUE TITLE
Add E2E Testing of Auth Flow in Development/Vercel

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#52]
The auth flow is in place. To authenticate, an A12n logins in with their WP.com credentials. Then they accept/denies the request for OAuth from Abacus.

But how do we test this with our E2E tests? We don't want to save credentials in the repo.

Note: If there are different user types/roles, then we should test the difference between them. That is, if Abacus should behave differently based on the user's type/role, then that should be tested.

**Comment by yanirs** [comment]
Closing since it's unlikely we'll get to this anytime soon, if at all.
