### ISSUE TITLE
Apply metric-level result redesign

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#524]
After the design and analysis adjustments are complete, we can then implement the experiment results summary table in Abacus!

**Edited by Yanir**: The discussion led to the design in pbmo2S-LK-p2#comment-1911. @jessie-ross can decide how to best split the work to PRs, but here are the main elements of the redesign:

- [x] Card-based design for the expanded metric assignment view
- [x] Summary card at the top, which includes an English explanation of the recommendation, the metric description, and last analysis date (see 641-gh-Automattic/experimentation-platform for the recommendation wording) 
- [x] Analysis card below the Summary card
- [x] Time series plots following the Analysis card
- [x] Collapsed observed data table as a panel at the bottom

**Comment by jessie-ross** [comment]
This is looking great @aaronyan, thanks for pushing this idea forward!

Love the small details like putting attribution window into parentheses and it is easy to see how this extends to A/B/n - I think we just need a selector with the diff graph to show the difference between different variations.

It's all straightforward to build :-)
