### ISSUE TITLE
Add leading space for non-negative values for top-level metrics

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#537]
What do y'all think about adding a leading space for top level metrics that start with a non-negative value? Because we're using a monospace font, it acts as an easy spacer for the top-level metrics to be aligned left. Here's a sample of what that may look like:

## Before
![Screen Shot 2021-05-20 at 2 48 23 PM](https://user-images.githubusercontent.com/4505888/119053092-71b88980-b97a-11eb-8cc7-e95822a31dbe.png)

## After (with leading space)
![Screen Shot 2021-05-20 at 11 12 27 AM](https://user-images.githubusercontent.com/4505888/119053038-5e0d2300-b97a-11eb-9a2a-c4813b7beb8f.png)

**Comment by yanirs** [comment]
I'm not too fussed. Another option is to add a + rather than a space, which may also read nicer when the range crosses zero (e.g., `-0.02 to +0.07 USD`).

**Comment by yanirs** [comment]
Actually, I prefer the `+` to a space since it'd make it easy to scan and see whether the changes are positive. This would go well with always showing two decimal points, as the meaning of `+0.00` (slightly higher than zero) is different from `-0.00` (slightly lower than zero).

**Comment by aaronyan** [comment]
Ooo nice, yeah I like the idea of having a `+`. In most of my reporting for experiment results on P2, I end up using `-` and `+` for the difference interval and lift % interval, so this matches that style perfectly.

**Comment by yanirs** [comment]
Great. :slightly_smiling_face:
@jessie-ross if you're on board as well, maybe you can add it along with the fix of the lift tooltip?

**Comment by jessie-ross** [comment]
Sure 🙂 

This kind of thing is what I was going for with the spacing but I think I went a bit too far.

Ideally we would be able to have a split header like this but it isn't possible with material table:

![download](https://user-images.githubusercontent.com/971886/119078090-18a72f00-ba28-11eb-9e10-3eaf05ab0154.png)

**Comment by yanirs** [comment]
Closed by #538
