### ISSUE TITLE
Link wiki to code setup tab

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#549]
We discussed in our milestone planning meeting that we think it's a good idea to change the "code setup" tab to **simply link to the experimenter's guide** [writing code variants](https://github.com/Automattic/experimentation-platform/wiki/Experimenter's-Guide#writing-the-controlvariant-code-experiences) section. This will help clean up that tab, because we don't think many experimenters use it. We should make sure to open new tab when the tab is clicked (instead of redirecting current window).

**Comment by jessie-ross** [comment]
This has been implemented at some point.
