### ISSUE TITLE
Show partial results without a primary metric analysis

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#554]
When looking into a recent A/A experiment, I noticed that the result page shows the "No Results" message even though it has thousands of participants. This appears to be due to the change in #543: The primary metric has no metric estimates, but participant counts and secondary metric estimates do exist. I think we should still show the results we have in such cases.

Marking this as a medium priority bug because it'd be experienced as a bug by experimenters: They get a Slack message saying that there are thousands of participants, but when they click the link to see the results it says "No Results". I think it's medium priority because it's unlikely to happen much in practice &ndash; in A/A experiments it may happen because we randomly assign metrics that have nothing to do with the experiment and the backend still doesn't handle the all-zero case well.

As part of the fix, it'd be good to pull out some of the logic from `ActualExperimentResults` and test it, as we seem to keep hitting bugs around the display of missing analyses. I think it also makes sense to show the analysis strategy selector if only some strategies have participants.

**Comment by jessie-ross** [comment]
Oh I had assumed that if an experiment didn't have primary MA estimates the secondaries wouldn't have either.

Can you link the A/A in question?

**Comment by yanirs** [comment]
> Oh I had assumed that if an experiment didn't have primary MA estimates the secondaries wouldn't have either.

It's a fair assumption. It technically shouldn't happen with a properly-configured experiment, and should be better once 574-gh-Automattic/experimentation-platform is resolved.

> Can you link the A/A in question?

Yep, it's 20202.

**Comment by jessie-ross** [comment]
I think we can fix this simply by adding a "Also change default strategy" switch under the Strategy selector

**Comment by yanirs** [comment]
What do you mean? Add a different default strategy setting to the experiment?
