### ISSUE TITLE
Emphasize and suppress top-level results by significance

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#555]
We received some feedback (pbmo2S-MY-p2#comment-1931) to distinguish statistically significant results. We show a ton of numbers and ranges, and it may be beneficial (and an educational opportunity) to emphasize/ suppress top-level metrics by their results statistical and/or practical significance.

We could use **font styles** to emphasize important results:
- Color results light grey (`rgb(204, 202, 202)`) if not statistically significant
- Color results current grey (`rgb(117, 117, 117)`) if statistically significant but not practically significant
- Color results `rgba(0, 0, 0, 0.87)` with font weight of `600` if statistically significant and practically significant (same style as metric name)

We could then **add an info icon** somewhere in the header educating experimenters about these three styles. What do y'all think? 

If we like this, we can consider combining this issue with https://github.com/Automattic/abacus/issues/524. I created this new issue, so we can discuss without creating noise in that issue.

Here's a mockup of what these style would look like:

![Screen Shot 2021-06-16 at 11 35 51 AM](https://user-images.githubusercontent.com/4505888/122276557-c11aa880-ce99-11eb-9032-34a48c710ac6.png)

**Comment by jessie-ross** [comment]
Yeah this looks like a good idea.

**Comment by yanirs** [comment]
Yeah, I think something like this would work, though I wonder about the "statistically significant but not practically significant" bit. Generally, we don't want to encourage too much reliance on statistical significance, since it can easily be misleading (especially early in the experiment). It's also unclear at a glance where the difference in shading comes from, as both cases are inconclusive.

How about we go with two shades initially (current grey and the darker variant), and take it from there?

**Comment by aaronyan** [comment]
Two shades sounds good to me for now! I would prefer having the light grey + dark grey (no current grey) if we have the two shade mix, as to de-emphasize inconclusive results. So we would only emphasize significant and practical results with dark grey, everything else is light grey.

**Comment by yanirs** [comment]
From the screenshot, the new light grey is too hard to read, to the point of making it less user friendly. I think that simply emphasising the significant results would be good enough, though if we want to make the inconclusive results lighter we could use the grey from the health report, which is a bit lighter than the current version but no illegible.

**Comment by aaronyan** [comment]
Yeah, that's fair. I think the idea was to make it hard to read to suppress the emphasis of certain top-level results. But as you mention, making it so hard to read that it leads to a bad user experience is probably something we want to avoid. Simply emphasizing with the dark grey may be enough!

Thanks for trying to find a compromise! I'm cool with using the current grey or the health report grey. :) Let's go with the health report grey for now, and we can iterate more if we need. I like the idea of those two tables have some shared styles!

**Comment by aaronyan** [comment]
Closing this issue since we're adjusting the recommendation wording and visualizations here (690-gh-Automattic/experimentation-platform).
