### ISSUE TITLE
Consider switching auth token storage to session rather than local

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#57]
On #44, @withinboredom suggested using `sessionStorage` rather than `localStorage` to store the auth token. I'm not sure this is worth doing, as clicking to login for every new tab (and potential embeds) can get cumbersome.

@dhurlburtusa  @withinboredom Let's use this issue for a quick discussion and make a decision.

**Comment by dhurlburtusa** [comment]
Now-a-days, many times `sessionStorage` and `localStorage` are almost equivalent with browsers letting you pickup where you left off the last time the browser was open (assuming the user has configured their browser to behave that way). That is, the same session can persist across browser and even OS restarts.

@withinboredom I definitely agree with the security principle of minimizing attack surface area.

@yanirs Right now, the auth token is the only thing using `localStorage`, it would just be a matter of a search and replace to update the code. But yeah, it might be annoying to have to re-auth just by opening a new tab with the same origin.

**Comment by yanirs** [comment]
> Now-a-days, many times `sessionStorage` and `localStorage` are almost equivalent with browsers letting you pickup where you left off the last time the browser was open (assuming the user has configured their browser to behave that way). That is, the same session can persist across browser and even OS restarts.

@dhurlburtusa do you have a reference for that? [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage):

* A page session lasts as long as the browser is open, and survives over page reloads and restores.
* Opening a page in a new tab or window creates a new session with the value of the top-level browsing context, which differs from how session cookies work.
* Opening multiple tabs/windows with the same URL creates sessionStorage for each tab/window.
* Closing a tab/window ends the session and clears objects in sessionStorage.

Looking at Scorecard code, it uses localStorage, so I'm inclined to do the same in our case.

**Comment by dhurlburtusa** [comment]
@yanirs I don't have a reference. If I recall correctly, I thought I read it somewhere on developers.google.com. I may be remembering incorrectly and I never tested to confirm it.
Note: Didn't mean the session would be the same when opening a new browser context (new tab/window) but when exiting the browser from the menu and having "On Startup" set to "Pick up where you left off".
Note: I was not advocating either way.

**Comment by withinboredom** [comment]
Let's use localstorage :)

**Comment by yanirs** [comment]
Reopening as @jessie-ross added issue #132 and said:

> Storing secure tokens in localStorage is unsafe as it can be accessed by any other code running on the site:
https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-storage-on-client-side

Looking at the link, their proposed solution is:
> * Store the token using the browser sessionStorage container.
> * Add it as a Bearer HTTP Authentication header with JavaScript when calling services.
> * Add fingerprint information to the token.

However, it seems like switching to `sessionStorage` is a solution to the second problem they note, where the token is "retrieved even if the browser is restarted". Despite the previous discussion, I don't mind switching to `sessionStorage` and seeing how it goes in terms of the need to log in. 

Regardless of the storage we choose, it seems like the more concerning security issue is it being accessible for any code that runs on the site. Isn't this concern an issue with `sessionStorage` as well, @jessie-ross?

**Comment by jessie-ross** [comment]
tldr; SessionStorage is the same problem, the token should be stored in memory.

We use JWT Authentication, they are entirely different from cookies.
By design, we don't handle whether users stay logged in or not, our Auth Provider - WordPress does.

Authentication is saved on disk, but on WordPress's Auth Server.

Instead of fetching the token from storage, we fetch it from our Auth Provider.

 as we are using means we aren't responsible authenticating and , the Authentication Provider - in this case WordPress is. This allows WordPress Auth to have full control over how long they want sessions to last.

All we have to do is:
1. Get a new token each time
2. Store that token in memory
3. Handle token expiry (This has to be handled whether we are storing on disk or not, for the MVP this can be a known bug).

I will attach a proposed PR with fix.

**Comment by yanirs** [comment]
> tldr; SessionStorage is the same problem, the token should be stored in memory.

How would we persist across tabs and browser restarts then? Having to authenticate for every new page load would get tedious.

> Store that token in memory.

Looks like storing the token in memory is problematic as well, as [it's still vulnerable to XSS](https://medium.com/@benjamin.botto/secure-access-token-storage-with-single-page-applications-part-1-9536b0021321). I've only skimmed that article and its second part, but we should probably consider its advice and other options.

I have some other thoughts. I'll send you an internal link on Slack. :slightly_smiling_face:

**Comment by yanirs** [comment]
Closing this again since we're not making this change.
