### ISSUE TITLE
Fix long name UX

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#578]
> Sort of related: There are several places with view overflows even on wide displays. I tested by adding an experiment and metric named `explat_test_very_long_name_yes_this_name_is_very_long_and_it_still_fits_within_our_limits_will_it_look_good_though_who_knows`. With this:
> 
> * Experiment List looks good
> * Experiment Overview has several overflows
> * Metric List overflows
> 
> Can you please look into it? We can also split this into a separate issue since it's a general overflow problem.
> 

_Originally posted by @yanirs in https://github.com/Automattic/abacus/issues/176#issuecomment-887114230_

**Comment by jessie-ross** [comment]
I can't see anywhere it is particularly affecting experiment names so that leaves metrics.

Since merging #540, we have fixed the only place experimenters have seen an overflow, and improved metric names so overall they are shorter.

Marking as low as it doesn't seem likely users will bump into this and if they do it is a pretty minor concern.

**Comment by yanirs** [comment]
I disagree with this being a low priority. Experimenters do hit long name issues, e.g., with exposure event names.

I think we should address this before it gets reported by experimenters.

**Comment by aaronyan** [comment]
Good idea on breaking this out as it's own issue. I'm a fan of increasing priority if the fix is quick and simple (maybe some trailing ellipses and more details on hover)!
