### ISSUE TITLE
Consider Running Tests during Pre-Commit Hook

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#60]
Currently, the pre-commit hook runs a formatting check and linters. Consider also running unit and e2e tests too. Right now, the unit and e2e tests don't take too long to run since we don't have much.

We can also just run unit tests.

We can also just run unit tests that pertain to the files that were committed. See https://benmccormick.org/2017/02/26/running-jest-tests-before-each-git-commit/ for how this can be done.

**Comment by yanirs** [comment]
In my opinion, this would make commits a bit too slow. It's also not necessarily desirable to run all the tests on every commit, as you can expect them to fail while developing and incremental commits are a good idea. :slightly_smiling_face:

**Comment by yanirs** [comment]
After spending some time working on Abacus code, I think we can close this. We have CircleCI to check that all tests pass, and it's easy to run tests locally. The pre-commit hooks are already slowing things down. Adding a couple of minutes of testing to each commit would either make people commit less or skip the hooks, neither of which is a desirable outcome.
