### ISSUE TITLE
Fails to load if experiment is in an invalid state

### ISSUE THREAD

**Issue by withinboredom** [Automattic/abacus#606]
If an experiment fails to load due to a validation error, we should redirect the user to the wizard to rectify the situation instead of giving an error.

**Comment by jessie-ross** [comment]
I am favour keeping things the way they are here - error states should not occur and it might be dangerous for users to continue on with an error state. I'd rather they come to us - that way we get to know every time an experiment enters an error state and ensure no flow on effects occur.

**Comment by aaronyan** [comment]
I agree with keeping the failed state so that they reach out to us. Closing for now!
