### ISSUE TITLE
Allow editing of experiment P2 URL on any status

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#609]
## Context

Experimenters have [requested](p1637579946079600-slack-C7HH3V5AS) editing the experiment p2 URL after they were `disabled`. Currently, editing the p2 URL is allowed only during `staging` status.

Let's make it easy for experimenters to keep their experiments up to date with the right URLs.

Parent issue: https://github.com/Automattic/experimentation-platform/issues/946

## Possible solution

- [ ] Update experiment API validation (part of D111312-code)
- [ ] Allow editing of experiment P2 URL at any status of the experiment on the UI

**Comment by razvanpapadopol** [comment]
We also have a new case here: pddn20-rA-p2#comment-702
