### ISSUE TITLE
Remove gap on experiments overview page

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#610]
On page load, the `/experiments` page has a gap between the last column and the right-most border of the table container. When manually resizing the window, the table snaps to the right and the gap is gone (the state we want!). Added a screenshot here to show more what I mean!

I'm on Mac OS X 11.6 on M1 using Chrome version 95.0.4638.69.

<img width="1288" alt="Screen Shot 2021-11-22 at 2 08 21 PM" src="https://user-images.githubusercontent.com/4505888/142943020-772f7eac-8548-4434-99cb-85ff6d006a64.png">

**Comment by is4ac** [comment]
I experienced this same issue when converting the metrics table to use AG Grid (using the experiments table as a foundation). I think the fix was a simple 1 or 2 line code change, I can try to fix this real quick today.
