### ISSUE TITLE
Increase width of Name column on experiments overview page

### ISSUE THREAD

**Issue by is4ac** [Automattic/abacus#612]
An unintended side effect of fixing #610 was that now the experiments overview page looks like this:

<img width="1401" alt="Screen Shot 2021-12-02 at 7 39 51 PM" src="https://user-images.githubusercontent.com/1518252/144530264-c4c5ae5b-64e7-4f4b-9163-0c99d7a1784b.png">

Now all of the columns are equal width, but that hides a lot of the longer names of experiments. We should set default column widths so that the proportions of the grid look better.

Should be a simple fix, I could even tackle it after finishing my current task.

**Comment by aaronyan** [comment]
Great catch! +1 to default column widths for better proportions. Thanks for documenting and taking care of that!
