### ISSUE TITLE
Move e2e tests to Teamcity

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#614]
Edit: We've decided to disable the e2e tests for now and will move the mover to Teamcity later (p7H4VZ-2Bs-p2).

It seems like CircleCI OOMs are failing our E2E tests.
(Although I haven't confirmed it is an OOM.)

Two options here:
- Decrease memory usage, I think there is a variable for Create React App that we could tune? Maybe something else?
- Increase CircleCI memory, not sure if this is doable...

**Comment by aaronyan** [comment]
Thanks for trying to fix the CircleCI e2e tests @is4ac! @jessie-ross and I discussed this during our 1-1 today, and we decided to disable these these tests for now, and we'll move them over to Teamcity later (p7H4VZ-2Bs-p2). Editing this issue to reflect this new direction!

**Comment by jessie-ross** [comment]
In the spirit of further simplification I think we should remove these e2e tests:
- Further complicates our dependencies, by a lot, puppeteer is very heavy.
- Provides no added value - it doesn't actually tell us if there is an issue with production, it instead tests a different environment.
- We don't need to ensure 99.999% uptime, it is ok if production fails temporarily.

**Comment by jessie-ross** [comment]
For context, these tests just spin up an mock Abacus, and clicks the navigation links, that's basically it.

**Comment by jessie-ross** [comment]
Since I was already working on our dependencies I've created a removal PR here:
https://github.com/Automattic/abacus/pull/858
