### ISSUE TITLE
Allow toggling of explat_test_ experiments

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#624]
Via @withinboredom, it would be a good idea to add a toggle in the experiments list to enable viewing all experiments including `explat_test_`.

**Comment by aaronyan** [comment]
It sounds like this is intended to give all experimenters access to those experiments, but I'm not sure if any experimenter needs to see `explat_test_` experiments.

We currently allow viewing `explat_test_` in debug mode. Would that be enough to close this issue?

**Comment by jessie-ross** [comment]
Yep, it's fine to close this.
