### ISSUE TITLE
Add Tests for ExperimentsApi.ts

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#65]
There are many ways to test the `api/ExperimentsApi.ts` since it makes actual fetch requests.

Unit tests can be created using mocks. The `fetch` function itself could be mocked. With this being mocked, what benefit are we really getting out of it? It would bypass the authorization code. It would test that we can mock a response that is parsable as JSON, the returned shape is correct, and we can correctly mimic the environment it will run in (browser with known `window.location.host` and `localStorage`).

To me, an integration test would be more beneficial than a unit test. Then the actual call using `fetch` is tested along with the authorization (assuming it is connected to an endpoint that using the authorization header).

An e2e test would be able to test the real thing in a real environment.

A lot of times with testing API calls, more work is involved creating mocks and setting up the appropriate environment. Sometimes I wonder if this is worth the effort.

**Comment by yanirs** [comment]
Good points. I think that an integration test makes sense in this case, as we already have a mock server.
