### ISSUE TITLE
Change health report colors

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#653]
With the introduction of new recommendations (690-gh-Automattic/experimentation-platform), I think we should reserve green and yellow to mean "actionable" / "inactionable". What do y'all think about changing the health report colors? Making the fields with potential issues more orange will also match the orange in the top-level report.

- Nominal - grey (#dadada4f)
- Potential issue - more orange (#fedb9d)

## Current
<img width="1250" alt="Screen Shot 2022-02-04 at 2 15 25 PM" src="https://user-images.githubusercontent.com/4505888/152610570-d9ff5f31-b6c9-407e-bfcc-32314b8324c5.png">

<img width="370" alt="Screen Shot 2022-02-04 at 2 24 15 PM" src="https://user-images.githubusercontent.com/4505888/152611282-80424098-8efa-4503-8f65-137f8688c309.png">

## Proposal
<img width="1244" alt="Screen Shot 2022-02-04 at 2 27 57 PM" src="https://user-images.githubusercontent.com/4505888/152611630-d038f46e-306b-4069-a969-744fab1266f7.png">

**Comment by jessie-ross** [comment]
This is much better!
