### ISSUE TITLE
Improve wording for "Deploy" action/recommendation

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#654]
There's a potential cause for confusion between the _Deploy_ ("Start experiment") button and the _Deploy either variation_ (or _treatment_ / _control_) recommendation.

<img width="499" alt="Screenshot 2022-02-08 at 21 39 04" src="https://user-images.githubusercontent.com/14192054/153062927-15316573-714b-487b-8776-ff6a13cda823.png">

After the introduction of the scary modal in https://github.com/Automattic/abacus/pull/424 we may reconsider the wording for the experiment start button introduced in https://github.com/Automattic/abacus/pull/422 . Can it be "Run" or even "Start"?

Related Slack thread: p1644341399120169-slack-C7HH3V5AS

## To-do
- [x] Rename "Deploy" to "Launch" for the experiment start button (#661)
- [x] Update wiki (FG)

**Comment by aaronyan** [comment]
Thanks for documenting @razvanpapadopol!

> reconsider the wording for the experiment start button introduced in https://github.com/Automattic/abacus/pull/422 . Can it be "Run" or even "Start"?

We use "Launch" in our wiki! We can consider changing the word to that.

**Comment by aaronyan** [comment]
> Update wiki (FG)

I've gone through the FG and changed "deploy" to "launch" when we mean "to start an experiment"!

> Update in-code documentation

Is there anything else here @razvanpapadopol, or can we close this?

**Comment by razvanpapadopol** [comment]
Thanks for updating the FG, @aaronyan ! 
I've also gone through the code references and I don't think there's anything else needed.
