### ISSUE TITLE
Improve disclaimer for deployment recommendation

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#673]
LE: this issue is being addressed in the following PRs:
1. https://github.com/Automattic/abacus/pull/699 to improve the deployment recommendation explainer
2. https://github.com/Automattic/abacus/pull/708 to highlight the primary metric by opening its details panel automatically

When displaying the deployment recommendation, we should try to clarify a couple of facts:
- what is the primary metric (specifically, for the current experiment)
- other metrics (secondary) were not taken into consideration when computing this recommendation so it's the responsibility of the experimenter to evaluate them when making a decision

<img width="483" alt="Screenshot 2022-04-08 at 10 48 43" src="https://user-images.githubusercontent.com/14192054/162390470-af478230-55bd-4e61-8edb-8d636cf67c7c.png">

**Comment by aaronyan** [comment]
I'd be open to improving this experience! How were you thinking of making it more clear what is the primary metric for the experiment?

**Comment by razvanpapadopol** [comment]
For the 1st point, I've tried to develop a method of programmatically expanding the first row of the Metric Assignment Results table but it's rather ugly code-wise. However, we can do small things like changing the label from "primary" to "primary metric" and maybe do something about the very transparent gray
<img width="672" alt="Screenshot 2022-05-13 at 21 10 45" src="https://user-images.githubusercontent.com/14192054/168342798-dafb46c2-57c5-466f-9fc2-976b9afe0f5b.png">

Secondly, I've been thinking to include a more detailed explanation/nudge as part of the deployment recommendation subtitle without taking so much real estate. Check out https://github.com/Automattic/abacus/pull/699

**Comment by aaronyan** [comment]
> For the 1st point, I've tried to develop a method of programmatically expanding the first row of the Metric Assignment Results table but it's rather ugly code-wise.

Ooo good idea! It may be worth drafting, since I've had some experience with folks not knowing you can expand the metric values. If it's in a draft, then @jessie-ross might be able to give some input.

> However, we can do small things like changing the label from "primary" to "primary metric" and maybe do something about the very transparent grey color that we're using.

I'm down for adding "primary metric". Great idea to make it consistent throughout. What did you have in mind to replace the transparent grey?

> Secondly, I've been thinking to include a more detailed explanation/nudge as part of the deployment recommendation subtitle without taking so much real estate. Check out https://github.com/Automattic/abacus/pull/699 PR with a proposal.

Very cool! Thanks for coding that up and sharing!

**Comment by jessie-ross** [comment]
> For the 1st point, I've tried to develop a method of programmatically expanding the first row of the Metric Assignment Results table but it's rather ugly code-wise.

Yeah I've tried this kind of thing before too, the grid library we use here is the issue, see #652 for AG-Grid enterprise possibility and also the new MUI grid is worth a look-in.

**Comment by razvanpapadopol** [comment]
> Ooo good idea! It may be worth drafting, since I've had some experience with folks not knowing you can expand the metric values. If it's in a draft, then @jessie-ross might be able to give some input.

Ugly or not, here's the draft for it: https://github.com/Automattic/abacus/pull/708/
UI-wise, I think it's quite smooth and it can be seen as a good addition until we decide on a more robust grid implementation.
