### ISSUE TITLE
Add 'copy to clipboard' button next to the experiment name

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#709]
A feature that might be useful when having to implement code, share an experiment or simply search for an experiment is the possibility to copy its name easily.

<img width="1267" alt="Screenshot 2022-05-20 at 19 56 39" src="https://user-images.githubusercontent.com/14192054/169576998-2a419035-1d78-4518-be8f-4aa9676c3284.png">

Here's an example from wp.com, after publishing a post:
<img width="349" alt="Screenshot 2022-05-20 at 19 47 50" src="https://user-images.githubusercontent.com/14192054/169577014-c5142e23-bf0f-4b15-b535-ecc8ee335ac9.png">

### Acceptance criteria:
- [ ] Implement the button next to the title
- [ ] Make sure the button is displayed correctly also when the title is displayed truncated (eg: `exp_name_...`)
- [ ] Add a confirmation after copying such as modifying the button label to "Copied!"

#### Bonus item:
* Add a possibility to quickly copy the experiment name in the "Create an experiment" wizard (on the last step maybe)

**Comment by aaronyan** [comment]
Yess! I love this idea. Good call on making sure it displays correctly even when truncating the title.

> Add a confirmation after copying such as modifying the button label to "Copied!"

Yes please on a confirmation like this. If we go with a copy icon, then maybe we can do a checkmark icon to confirm it's been copied. Something like these two?

- [CopyContent](https://mui.com/material-ui/material-icons/?query=copy&selected=ContentCopy)
- [AssignmentTurnedIn](https://mui.com/material-ui/material-icons/?query=checkmark&selected=AssignmentTurnedIn)

**Comment by razvanpapadopol** [comment]
Woah, I haven't seen those until now! ✨  
The jiggly feedback is fun but I'd try also with a checkmark, as Aaron suggested, for extra clarity.
