### ISSUE TITLE
Add absolute impact credible intervals

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#710]
What do we think about adding **absolute impact** credible intervals to the experiment results page like "# of users / month" and "$ in revenue / month"? This was originally suggested in this comment (pbmo2S-UZ-p2#comment-2110) and then analyzed with this method in this comment (pbxNRc-1qR-p2#comment-3353). 

In addition to the first two stats, let's consider adding a third stat "absolute impact" (we can iterate on the name!):
- Absolute change: [ -0.02pp, +0.07pp ]
- Relative change: [ -1.63%, +5.04% ]
- Absolute impact: [ -188, +659 ] / month or [ -4,036, +14,149 ] / year

Design questions:
- [ ] Where do we add this "absolute impact"? Just another column in the analysis table? Replace "absolute change"?
- [ ] Do we allow toggle-able date ranges (like per month vs per year)?

**Comment by aaronyan** [comment]
> Where do we add this "absolute impact"? Just another column in the analysis table? Replace "absolute change"?

I like @razvanpapadopol's proposal to replace absolute change with this absolute impact credible interval. I'd even recommend naming it to a simple 'Impact' to hint at "impact analysis".

I think we can also swap the order of the columns: name, relative change, impact, analysis. I think that order and progression of information helps tell a story:

1. What is the name of metric being analyzed?
2. What are the broad results (% lift)?
3. What kind of impact does that have (# of users, $)?
4. What's the analysis?

**Comment by jessie-ross** [comment]
Ah I think this should be another row in the intervals table rather than altering the metric assignments table, reason being that impact figures are a bit more fluffy and require a bit more understanding for interpretation than absolute change.

**Comment by aaronyan** [comment]
Mmm for sure. I can see how the estimated effects of impact can be more fluffy, and I'm down to add it as another row in the intervals table for the details of a metric!

For the metrics overview, I think the impact could be really nice as a column to help bring context to the relative change. Something like a relative change of +200% but has an impact of +10 more users is nice to know from the start imo!
