### ISSUE TITLE
Hide archived metrics in metric directory

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#719]
We hide `archived_*` metrics from the [autocomplete in experiment creation](https://github.com/Automattic/abacus/blob/cadabc0439f3d918b242353760f71f9bd99f8f86/src/components/general/MetricAutocomplete.tsx#L22). Let's also hide `archived_*` metrics when viewing the metric directory (but viewable in [debug mode](https://github.com/Automattic/abacus/blob/388cb11f3772581c796c534d9b75943775763f2c/README.md#debugmode)).

**Comment by aaronyan** [comment]
Ah good call! Yeah, there definitely is value in being able to explore archived metrics. I love the idea of adding a way to view the archived metrics!

**Comment by aaronyan** [comment]
I'm down to remove debug mode if we replace some of it's functionality like only allowing specific a12s to create Abacus metrics. What are the reasons for removing debug mode again?

**Comment by jessie-ross** [comment]
I think we should eventually allow A12s to create Abacus metrics, adding a warning (or maybe some "I have gotten this metric reviewed" checkboxes) on the form requiring a P2 post and a review from an experiment-reviewer.

My thoughts on this is that we should be removing ourselves from the loop a bit more, and as part of the culture of A8C I think we should trust experimenters a bit more. 

It will also make the development of Roles and Permissions unnecessary, simplifying things drastically.

**Comment by razvanpapadopol** [comment]
>  eventually allow A12s to create Abacus metrics

A possible option I see is doing this in 3 stages:
1. Add all the extra checks and guidance in the UI. 
2. Extend the list of a12s allowed to create metrics to at least all the graduates of the Experimenter Reviewer training (pbmo2S-16u-p2) so we have more folks enrolled in the "beta testing" of the guided process.
3. Open for everyone and cleanup Roles and Permissions 🎉 

> adding a warning (or maybe some "I have gotten this metric reviewed" checkboxes)

Sounds cool! 👍🏼 
Also a link to documentation (PCYsg-Fqe-p2) would be nice to have.

> requiring a P2 post

Oh yes, that would be good for documentation no matter who's adding metrics. I've just noticed a good example recently: pbmo2S-1ov-p2#comment-2364

Random thought: we should probably take this to another issue or just rename this one after hiding the archived metrics

**Comment by aaronyan** [comment]
Sorry I missed the notifications on this conversation and for responding so late! 😅 Thanks for sharing your thoughts @jessie-ross and @razvanpapadopol.

> 1. Add all the extra checks and guidance in the UI.
> 2. Extend the list of a12s allowed to create metrics to at least all the graduates of the Experimenter Reviewer training (pbmo2S-16u-p2) so we have more folks enrolled in the "beta testing" of the guided process.
> 3. Open for everyone and cleanup Roles and Permissions 🎉

I prefer to have only ExPlat team + experiment review graduates add/remove metrics. It's definitely part of the a8c culture to give all the freedoms, but I see experiment metric requests providing a review and protection similar to a systems request. Same idea for experiment reviews!

I like the three stage approach for now, and we can revisit stage 3. Experiment culture may be robust enough for any a11n to add/remove metrics on Abacus.

> Adding a warning (or maybe some "I have gotten this metric reviewed" checkboxes)
> Also a link to documentation (PCYsg-Fqe-p2) would be nice to have.
> requiring a P2 post
> Random thought: we should probably take this to another issue or just rename this one after hiding the archived metrics.

Those sound like great improvements to me too. I'll create a separate issue with those suggestions.

**Comment by razvanpapadopol** [comment]
Closing in favour of https://github.com/Automattic/experimentation-platform/issues/912
