### ISSUE TITLE
Allow search by metric definition

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#723]
We should allow search by metric definition in the metric directory. If an experimenter knows the Tracks event, but doesn't know the metric name in Abacus, this will significantly make it easier to find the right metric.

Looking at out [APIs and schemas](https://app.swaggerhub.com/apis/yanir/experiments/0.1.0#/management/get_metrics), it doesn't look like this would require a change to the API!

**Comment by razvanpapadopol** [comment]
Yes, it looks like we have everything we need 🎉 
I've drafted the new functionality in https://github.com/Automattic/abacus/pull/725 using the same pattern as in the experiment directory search by description (https://github.com/Automattic/abacus/pull/692).
