### ISSUE TITLE
Metric Assignment Results: Preserve the rows open state

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#731]
I just noticed that the result rows auto-collapse when changing the controls too. Would it be possible to leave opened results rows open on controls change? This is not very important so if it takes a lot of work, I say we ship your changes just like this (just a nice quality of life thing)!

_Originally posted by @aaronyan in https://github.com/Automattic/abacus/issues/726#issuecomment-1149275765_

After some investigation, it looks like this behavior also applies to changing the Analysis Strategy.

Related thread (no straight-forward solution): https://github.com/mbrn/material-table/issues/1021

**Comment by aaronyan** [comment]
Thanks for moving this request to a separate issue, @razvanpapadopol! Too bad there's not a straight-forward fix.
