### ISSUE TITLE
Change default tabs for non-staging experiments

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#742]
When clicking an experiment from the experiment directory, we always default to the Overview tab. What do y'all think about defaulting to a Overview tab for `staging` experiments and Results tab for all other statuses?
- `staging` - Overview tab
-  `running` - Results tab
- `completed` - Results tab
- `disabled` - Results tab

**Comment by jessie-ross** [comment]
Yep! I love this one! I had this as a fleeting thought a while ago.

In fact, I was thinking we could even integrate the two, maybe with an summary/detailed switchable overview.

**Comment by razvanpapadopol** [comment]
Yes, I don't see a reason why we shouldn't do this. I was also working to design a solution to show the description in the experiment directory (second point of https://github.com/Automattic/abacus/issues/500) that would help when identifying an experiment before clicking.

**Comment by aaronyan** [comment]
Love all the ideas for improving usability around the overview and results. I'm open to iteration!
