### ISSUE TITLE
Add % of users field to experiment definition

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#748]
While on the data leads call today, I learned that pipe experiments (ML sales) only target 5% of users which would underestimate the absolute impact (https://github.com/Automattic/abacus/issues/710). If we add a field in experiment creation on what % of users are being experimented on, then we can add a multiplier to better estimate the absolute impact. This field would be optional and hidden, and it would require quite a few changes:

Changes required:
- [ ] Add new column to `wpcom.experiments` to save targeted % of users
- [ ] Adjust `GET /experiment/{experiment_id}` endpoint to return new field
- [ ] Add new field to experiment creation
- [ ] Add new field to experiment summary
- [ ] Add new field calculation to adjusted absolute impact (`1/{targeted_percentage} * # of participants`)

**Comment by jessie-ross** [comment]
I don't quite understand this? Wouldn't the treatment variation percentage be set to 5%?

**Comment by aaronyan** [comment]
Oh good call. Yeah, that is much more simple!

ML sales experiments will use the manual assigner, so setting 5% `treatment` won't have any affect on actual assignment. And then we can use the 5% `treatment` value to indicate the multiplier for absolute impact. Closing this issue for now!

**Comment by jessie-ross** [comment]
We also have the actual number of participants per variation and would really want to calculate from that.
