### ISSUE TITLE
Allow for decimal allocation percentages

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#750]
Some experiments are run as non-50/50 split and will naturally have repeating values like 1/3 (33.33%). Because we do not allow any decimals in allocated percentages, experiments with high participant counts may receive a false positive in their assignment distribution health report ([example](pbmo2S-1tT-p2-p2)). Let's consider allowing decimal allocation percentages, but default to integer when adding up/down using the arrow keys.

- [ ] Allow decimal allocation percentages
- [ ] Default to 1/n allocation for A/B/n experiments
- [ ] Add default "split evenly" toggle. If turned off, allows experimenters to customize allocation

**Comment by razvanpapadopol** [comment]
I agree that allowing decimal allocation percentages it's a sensible thing to do and, as a way to showcase it, we can change the defaults to 33.33% when the user adds a third variation (same as we're displaying 50/50 at initial load).

As an alternative (or follow-up), WDYT of adding a toggle "Use even split" that is enabled by default so we display the allocation percentages as read-only unless a user explicitly wants to modify them?

**Comment by aaronyan** [comment]
I like both those ideas! I've added them as checklist items to consider when resolving this issue.

**Comment by jessie-ross** [comment]
This should only ever be an issue for manual assignment experiments - which use the API and not Abacus, so I don't think we should allow decimal points in percentages in Abacus.

Even in the case of manual assigners they are able to set the target percentages - they should be picking round percentages to keep things simple, the amount they would gain from decimal percentages is rather small.

> As an alternative (or follow-up), WDYT of adding a toggle "Use even split" that is enabled by default so we display the allocation percentages as read-only unless a user explicitly wants to modify them?

I don't mind this as a separate idea, but I kinda also like that experimenters have to take a moment to think about their percentages, and I don't think it is a big time saver for them.

**Comment by jessie-ross** [comment]
This is also a big change because 100 percentage points correspond to our 100 buckets, so we'd need to make changes to the assigner here too.

**Comment by razvanpapadopol** [comment]
> This should only ever be an issue for manual assignment experiments

Alright, so if I want to run an A/B/C test with auto assignment and pick 33% for each variant, there won't be any false positive in the assignment distribution health report and I'll just miss targeting 1% (1 bucket). In this case, I agree that it's not worth switching to decimal percentages in Abacus.

> I don't think it is a big time saver for them

Yeah, probably not. We may suggest in the information field that an even split is recommended for quicker results. But we also have the experiment reviews 🔎

**Comment by aaronyan** [comment]
Closing this issue and opening in a new issue instead: https://github.com/Automattic/abacus/issues/786
