### ISSUE TITLE
Change min diff placeholders

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#763]
We are currently showing `5.4 pp` and `1.30 USD` as our min diffs placeholder, while most experiments run with min diff values of around `0.03 pp` and `0.005` USD. I'm proposing we adjust the placeholders to be more in line with realistic values!

Currently showing:

<img width="1041" alt="Screen Shot 2022-08-16 at 4 38 02 PM" src="https://user-images.githubusercontent.com/4505888/185003543-c69d01ca-1b3c-43cc-b814-d5405216156f.png">

**Comment by razvanpapadopol** [comment]
Yes, this is something that may confuse especially first-time users. Thanks for documenting the issue and for researching more appropriate values!

I'm addressing it in https://github.com/Automattic/abacus/pull/764 with the mention that we shouldn't go to `.001` precision until https://github.com/Automattic/abacus/issues/752 is implemented.
