### ISSUE TITLE
Research replacing ExperimentTable with an existing component

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#77]
As discussed in https://github.com/Automattic/abacus/pull/74#discussion_r426334593, we should clarify the medium-term requirements around our tables and consider using a third-party solution rather than reinventing the wheel. Clarifying the requirements can happen on P2.

This issue is a blocker to work on any new tables.

**Comment by dhurlburtusa** [comment]
We decided to go with Material UI and Material Table.
