### ISSUE TITLE
Add new analysis columns

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#780]
After adding absolute impact to Abacus (https://github.com/Automattic/abacus/pull/772), I think we can change the way we show the results of the experiment:

- [ ] Display baseline interval below metric name p10gg3-aFD-p2#comment-33110.
- [ ] Rename "absolute change" to "estimated difference"
- [x] Rename "relative change (lift)" to "estimated impact". Done in https://github.com/Automattic/abacus/pull/772
- [ ] Reduce the font size and font color to a grey `#828282` of absolute change and relative change
- [x] Add absolute impact to "estimated impact" with medium weight. Done in https://github.com/Automattic/abacus/pull/772
- [ ] Adjust analysis text to be medium weight
- [ ] Align absolute change and relative change to be on the same horizontal ruler
- [ ] The gap between absolute impact and relative change should be vertically aligned with metric name and analysis text

<img width="1194" alt="Screen Shot 2022-09-16 at 3 18 32 PM" src="https://user-images.githubusercontent.com/4505888/190815505-bf891f65-2fd8-4dfa-aba8-973976b90063.png">

**Comment by razvanpapadopol** [comment]
A couple of these changes were already implemented with the release of estimated impact feature and the rest are all included in https://github.com/Automattic/abacus/pull/795 🚀 .

The only minor observation is the grey `#828282` being possibly a bit too light. Here's a comparison with `#616161` which is the `grey.A700` variable we're already using from the [default MUI color palette](https://mui.com/material-ui/customization/color/#color-palette).

<img width="686" alt="Screen Shot 2022-11-09 at 22 41 43" src="https://user-images.githubusercontent.com/14192054/200937937-c5cef1e0-028a-4af9-a87c-ccb1f0c6a8b1.png">
<img width="694" alt="Screen Shot 2022-11-09 at 22 39 46" src="https://user-images.githubusercontent.com/14192054/200937939-bdcf47fe-9be5-4d59-b3fd-921738b35423.png">
