### ISSUE TITLE
Experiment results: Impact Improvements 

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#792]
- [ ] Better vertically align the interval picker.
   <img width="281" alt="Screen Shot 2022-10-25 at 2 30 30 pm" src="https://user-images.githubusercontent.com/971886/197699155-7d29cff5-e547-494b-9e84-4d29df40ff1c.png">
- [ ] Update impact sentence in metric detail summary
   > we should include the number of participants over the time period as it is an important factor of the calculation.
   _Originally posted by @jessie-ross in https://github.com/Automattic/abacus/pull/772#discussion_r1001788759_
- [ ] Add "conversions" unit suffix to the top-level impact.

**Comment by jessie-ross** [comment]
I've made this issue a general impact improvements issue and added some more small tasks.

**Comment by razvanpapadopol** [comment]
Hey @jessie-ross ! Could you share some details on how to reproduce the misalignment of interval picker (first item here)? I've tried using various resolutions in Google Chrome and Safari without success.

**Comment by jessie-ross** [comment]
Ah I use Firefox 106.0.3, window size doesn't seem to matter. If it is a hard to find bug however, I can just live with it :-)
