### ISSUE TITLE
Add experiment details page

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#8]
Aaron edited: Let's make this details page the same as the second page in the New Experiment creation flow. We just need to add the p2 link to the "basic info" section underneath the experiment name.

When a user clicks on an experiment from the experiments list page, then they will be brought to this experiment details page. We'll likely have two tabs/sections on this page:

1. Analysis
2. Experiment details

We'll default to 1 if experiment has results, otherwise default to 2.

All the buttons will be greyed out (uneditable) until we have have the components to update the experiment details (#10).

**Comment by aaronyan** [comment]
> We'll likely have two tabs/sections on this page:

Let's add one more tab for "Snippets". We can rename this to "More" or "Extra" if we have more things we want to display for an experiment. Having the snippets here will be convenient for experimenters to use this page as a reference if they missed the success page during experiment creation.

**Comment by yanirs** [comment]
> All the buttons will be greyed out (uneditable) until we have have the components to update the experiment details (#10).

@aaronyan thinking about it in the context of #179, adding greyed out buttons isn't a great UX and the toolbar that @dhurlburtusa isn't necessarily the way we want to follow. I'll close this issue since we pretty much have the experiment details page, and add specific new issues for each edit action.

**Comment by yanirs** [comment]
Added #194, #195, and #196.
