### ISSUE TITLE
Add styling and site layout

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#80]
Once we have some mockups and styles, let's add them to Abacus! :)

Site layout:
- Headers, footers
- Menu, logo

Styling:
- Color scheme
- Font choices
- General style guides (margins, paddings)
- Heading and paragraph styles

**Comment by aaronyan** [comment]
> Styling

We're going with [Material UI](https://material-ui.com/) for our design framework. And then we'll likely go with a [paid theme](https://material-ui.com/store/items/devias-kit-pro/) to style the color, typography, spacing, and overall look and feel.

> Headers, footers
> Menu

The header and footer will be basic:
- Dashboard
- Experiments
- Metrics

We will likely use a vertical left-side navigation drawer to be mobile friendly and give it a more app-like feel.

> Logo

Still got to make one! :). We can use Experimentation Platform logo for now, but I think I would like to create an Abacus logo to better match the theme we choose.

**Comment by dhurlburtusa** [comment]
I'm removing myself from this as it is really an ongoing, team effort.

**Comment by aaronyan** [comment]
Closing this for now since these gets added over time, and I don't think we'll ever stop iterating on this.
