### ISSUE TITLE
Documentation links lead to internal (and private) sites

### ISSUE THREAD

**Issue by bgbg** [Automattic/abacus#801]
The site https://abacus-a8c.vercel.app/ is supposed to be a public demonstration of Abacus. 
[This page](https://abacus-a8c.vercel.app/experiments/3-experiment-name-123/wizard-edit) contains several links that are supposed to provide useful information and guidance. However, these links lead to the private field guide.
 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/506547/202417131-da0814bf-0d7a-414c-8e26-58d7af8b742b.png">

**Comment by razvanpapadopol** [comment]
Hi, @bgbg 👋🏼 
Thanks for reporting this issue! 
Together with https://github.com/Automattic/abacus/issues/803 that covers more code clean-up, we'll definitely add clarity to the public demonstration side of Abacus.

**Comment by bgbg** [comment]
@razvanpapadopol thanks
