### ISSUE TITLE
Impact on email experiments are incorrect

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#808]
I was looking at the impact of the recent black friday email experiment and noticed that the impact is incorrect as we are extrapolating the experiment over time when the experiment is a one-time thing.

We should disable impact for email experiments.

**Comment by aaronyan** [comment]
@demetd shared that we could report one-off experiments differently: estimated impact can be reported as the audience size * diff. Instead of disabling impact for email experiments, what if we default to reporting it as Demet suggested?

**Comment by razvanpapadopol** [comment]
Yes, this is definitely a case that needs fixing. Thanks, @jessie-ross and @kristinaquinones, for raising it! 
I've drafted a first version of what Demet suggested in https://github.com/Automattic/abacus/pull/809 so the impact + tooltip for the 3rd metric assigned to 20909-explat-experiment would look like this:
<img width="685" alt="Screenshot 2022-11-29 at 01 41 43" src="https://user-images.githubusercontent.com/14192054/204404939-2fb98ed3-c7fe-4e9f-a632-aa13a047d7c6.png">
