### ISSUE TITLE
Fix cash sales description to use USD units

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#825]
For experiments with cash sales metrics, the units of the cash sales metric should be `USD` and `USD per user`. It looks like there might be a bug in the description of the details where the cash sales metrics are showing units for conversion metrics(`pp` and `conversions`).

<img width="1256" alt="Screenshot 2023-01-04 at 2 51 19 PM" src="https://user-images.githubusercontent.com/4505888/210677816-f1f26f7c-2f9d-4284-8dee-ce57830ac830.png">

This example is from the experiment: 20846-explat-experiment

### To do

- [ ] Fix cash sales description to match units

**Comment by razvanpapadopol** [comment]
Thanks for reporting and documenting this bug, @aaronyan ! 
There's also a similar problem if we look below, at the _Absolute change_ column of the Analysis table and at the _Experimenter-set minimum practical difference_ value.

<img width="856" alt="Screenshot 2023-01-05 at 22 50 30" src="https://user-images.githubusercontent.com/14192054/210881751-9591b359-84b6-4482-b8fd-e9f5323429d3.png">
