### ISSUE TITLE
UI crashing because of 'explat_test_'  metric assigned

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#848]
## Context

UI crashing for a specific experiment - 20938-explat-experiment as mentioned in 
p1676386757691059/1676317539.612699-slack-C7HH3V5AS

When in debug mode, the experiment works fine.

## Current Behavior vs Expected Behavior

Like every other experiment, it should load.

This one stops loading with these error messages as tested:

* Overview:
`Failed to lookup metric with ID XXX for assignment with ID XXXX.`

* Results:
`Error: Could not find matching unit-type for metric and derivations.`

## Possible Solution

Check the latest changes related to introducing pipe params and see why it works in `debug` mode.

LE: Fetching all metrics (add `?debug` parameter) for experiments page (Overview and Results tabs) and filtering out by name excluding `explat_test_` seems like a good fix.
*Removing completely the `?debug` filtering on the backend and using the same client-side filtering also on Metrics page and Experiment Wizard could be a potential simplification.

**Comment by razvanpapadopol** [comment]
I've managed to track this issue to this check for metric name: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Srkcrevzragf%2Spynff%2Qdhrel%2Qurycref.cuc%3Se%3Q92708qp7%23428-og

**Comment by jessie-ross** [comment]
[I replied here](p1676428868321399/1676317539.612699-slack-C7HH3V5AS), and DM'd Dusty to resolve the immediate issue.

For the general fix I suggest fetching all metrics for experiments page, and filtering out debug experiments where necessary.

**Comment by razvanpapadopol** [comment]
> fetching all metrics for experiments page

Indeed, this seems the only way to know which metric assignment to hide as we need to go over the names first. I'll update the issue with next steps.
