### ISSUE TITLE
Have analysis method be encoded in the URL state

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#884]
From p1687883275481119/1687160385.770289-slack-C7HH3V5AS

We should have the analysis method be stored in the URL state:
e.g. `/experiments/1000-experiment-name/results?analysis-method=assigned`

This would allow results to be shared and linked to the correct method.

**Comment by razvanpapadopol** [comment]
Hey, @jessie-ross ! I was working at something similar just now so managed to quickly come up with this solution: https://github.com/Automattic/abacus/pull/885
