### ISSUE TITLE
Test more ExperimentsTable Functionality

### ISSUE THREAD

**Issue by dhurlburtusa** [Automattic/abacus#93]
Not all functionality has been tested with the ExperimentsTable. Some of the pagination functionality has been tested but more could be done. The search box is not being tested (at least not by us, it may be tested by Material Table). There is talk about adding filtering which would then need to be tested. Testing the sorting feature may be useful.

**Comment by yanirs** [comment]
Now that we're using a third-party component, I think we can make the testing pretty light and rely on Material Table to do the right thing. Agreed with this being a low priority. :slightly_smiling_face:

**Comment by dhurlburtusa** [comment]
I think we can close this. I don't think there is anything else we can test that MaterialTable isn't already testing.
