### ISSUE TITLE
Analysis UI: Add trends over time

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#97]
Once #95 and #96 are resolved, we should:

* Choose a plotting library
* Show CIs over time
* Show participant counts over time

**Comment by aaronyan** [comment]
We'll likely want to discuss on P2 how we want to visualize this analysis UI:

- [ ] P2 and discuss analysis UI: plotting libraries, visualizations (likely CI and participant counts over time)*
- [ ] (Optional) Mock up what the analysis UI will look like after the P2 discussions
- [ ] Add (the P2-decided) visualizations to Abacus

*if it's easier, the discussions can happen over multiple P2s

**Comment by aaronyan** [comment]
There's quite a bit on @jessie-ross's plate this milestone, so added @yanirs back to this issue. When we have availability between onboarding new experimenters, @yanirs can you help us kick-off the P2 discussion around the trends over time visualizations?

**Comment by yanirs** [comment]
Sure :slightly_smiling_face:

**Comment by aaronyan** [comment]
Thanks @yanirs!

**Comment by jessie-ross** [comment]
This is mostly resolved by #334, do we still want to have participant counts over time?

**Comment by aaronyan** [comment]
I'd really like participant counts over time! :) I think it's an easy graph for folks to understand that builds confidence in the tool. Also happy to add this later if we'd like.

If we do, we could create another table above/below the metrics called "General Stats". And the first collapsable row be "Participant counts". We could leave that summary row empty for now, but I could easily see that row being a summary of the % split and an HDV like calculation showing the "health" of the split.

Anyway, I'm getting a bit ahead of myself. What do y'all think? Shall we include participant counts over time here?

**Comment by yanirs** [comment]
Yeah, I think we should include overall participant counts over time, but we need to resolve the issue with the metrics not all being analysed to the same date. In any case, for Abacus, we can use the counts from the primary metric, as they will align with the other counts once the ETL issue is fixed. 

We can also split this issue if we feel like closing it after #334 is merged. :slightly_smiling_face:
